dist: trusty
sudo: required
language: node_js
addons:
  chrome: stable
node_js:
  - "7"
  - "node"

script:
  - npm run test
  - npm run lint

deploy:
  provider: script
  script: deploy.sh
  on:
    all_branches: false
    condtion: $TRAVIS_BRANCH =~ ^dev$