// This is a generated file from bundleLocFiles.js 

export const loc_strings = {};

loc_strings['en-US'] = {
  "To try the explorer, please ": "To try the explorer, please ",
  "sign in": "sign in",
  " with your work or school account from Microsoft.": " with your work or school account from Microsoft.",
  "Submit": "Submit",
  "Using demo tenant": "You are currently using a sample account.",
  "To access your own data:": "To access your own data:",
  "sign out": "sign out",
  "History": "History",
  "Method": "Method",
  "Query": "Query",
  "Status Code": "Status Code",
  "Duration": "Duration",
  "Go": "Go",
  "milliseconds": "ms",
  "YES": "YES",
  "Show More": "show more",
  "Graph Explorer": "Graph Explorer",
  "Failure": "Failure",
  "Success": "Success",
  "Authentication": "Authentication",
  "NO": "NO",
  "request header": "Request Headers",
  "Run Query": "Run Query",
  "request body": "Request Body",
  "Close": "Close",
  "Getting Started": "Getting Started",
  "Response": "Response",
  "login to send requests": "Login to change the request type",
  "Share Query": "Share Query",
  "Share this link to let people try your current query in the Graph Explorer.": "Share this link to let people try your current query in the Graph Explorer.",
  "Date": "Date",

  "my profile": "my profile",
  "my files": "my files",
  "my photo": "my photo",
  "my mail": "my mail",
  "my manager": "my manager",

  "Response Headers": "Response Headers",
  "Response Preview": "Response Preview",
  "Sample Queries": "Sample Queries",

  "show more samples": "show more samples",
  "Sample Categories": "Sample Categories",

  "On": "On",
  "Off": "Off",
  "Remove All": "Remove All",

  "Enter new header": "Enter new header",

  "Key": "Key",
  "Value": "Value",

  "Login to try this request": "Login to try this request",

  "modify permissions": "modify permissions",
  "Save changes": "Save changes",
  "To change permissions, you will need to log-in again.": "To change permissions, you will need to log-in again.",

  "all the items in my drive"	:"all the items in my drive",
  "items trending around me"	:"items trending around me",
  "my direct reports"	:"my direct reports",
  "all users in the organization"	:"all users in the organization",
  "all users in the Finance department"	:"all users in the Finance department",
  "my skills"	:"my skills",
  "all my Planner tasks"	:"all my Planner tasks",
  "track user changes"	:"track user changes",
  "all groups in my organization"	:"all groups in my organization",
  "all groups I belong to"	:"all groups I belong to",
  "unified groups I belong to"	:"unified groups I belong to",
  "group members"	:"group members",
  "group's conversations"	:"group's conversations",
  "group's events"	:"group's events",
  "add favorite group"	:"add favorite group",
  "items in a group drive"	:"items in a group drive",
  "track group changes"	:"track group changes",
  "my high important mail"	:"my high important mail",
  "my mail that has 'Hello World'"	:"my mail that has 'Hello World'",
  "send an email"	:"send an email",
  "forward mail"	:"forward mail",
  "track email changes"	:"track email changes",
  "email I'm @ mentioned"	:"email I'm @ mentioned",
  "my events for the next week"	:"my events for the next week",
  "all events in my calendar"	:"all events in my calendar",
  "all my calendars"	:"all my calendars",
  "all my event reminders for next week"	:"all my event reminders for next week",
  "find meeting time"	:"find meeting time",
  "schedule a meeting"	:"schedule a meeting",
  "track changes on my events for the next week"	:"track changes on my events for the next week",
  "my contacts"	:"my contacts",
  "add contact"	:"add contact",
  "my recent files"	:"my recent files",
  "files shared with me"	:"files shared with me",
  "all of my excel files"	:"all of my excel files",
  "create a folder"	:"create a folder",
  "create session"	:"create session",
  "worksheets in a workbook"	:"worksheets in a workbook",
  "add a new worksheet"	:"add a new worksheet",
  "used range in worksheet"	:"used range in worksheet",
  "tables in worksheet"	:"tables in worksheet",
  "charts in worksheet"	:"charts in worksheet",
  "all Planner plans associated with a group"	:"all Planner plans associated with a group",
  "all Planner tasks for a plan"	:"all Planner tasks for a plan",
  "my organization's default SharePoint site"	:"my organization's default SharePoint site",
  "a SharePoint site by URL"	:"a SharePoint site by URL",
  "subsites in a SharePoint site"	:"subsites in a SharePoint site",
  "list in a SharePoint site "	:"list in a SharePoint site ",
  "my notebooks"	:"my notebooks",
  "my sections"	:"my sections",
  "my pages"	:"my pages",
  "create notebook"	:"create notebook",
  "create section"	:"create section",
  "create page"	:"create page",
  "Users":"Users",
  "Users (beta)":"Users (beta)",
  "Groups":"Groups",
  "Groups (beta)":"Groups (beta)",
  "Outlook Mail":"Outlook Mail",
  "Outlook Mail (beta)":"Outlook Mail (beta)",
  "Outlook Calendar":"Outlook Calendar",
  "Outlook Calendar (beta)":"Outlook Calendar (beta)",
  "Personal Contacts":"Personal Contacts",
  "OneDrive":"OneDrive",
  "Excel":"Excel",
  "Planner (beta)":"Planner (beta)",
  "SharePoint Sites (beta)":"SharePoint Sites (beta)",
  "OneNote (beta)":"OneNote (beta)",
  "SharePoint Lists (beta)": "SharePoint Lists (beta)",
  "Insights": "Insights",
  "Insights (beta)": "Insights (beta)",
  "Preview": "Preview"
}

loc_strings['de-DE'] = {
  "To try the explorer, please ": "Um den Tester auszuprobieren, ", 
   "sign in": "melden Sie sich", 
   " with your work or school account from Microsoft.": " mit Ihrem Geschäfts-, Schul- oder Unikonto von Microsoft an.", 
   "Submit": "Senden", 
   "Using demo tenant": "Sie verwenden derzeit ein Beispielkonto.", 
   "To access your own data:": "So greifen Sie auf Ihre eigenen Daten zu:", 
   "sign out": "Abmelden", 
   "History": "Verlauf", 
   "Method": "Methode", 
   "Query": "Abfrage", 
   "Status Code": "Statuscode", 
   "Duration": "Dauer", 
   "Go": "Gehe zu", 
   "milliseconds": "ms", 
   "YES": "JA", 
   "Show More": "Mehr anzeigen", 
   "Graph Explorer": "Graph-Tester", 
   "Failure": "Misserfolg", 
   "Success": "Erfolg", 
   "Authentication": "Authentifizierung", 
   "NO": "NEIN", 
   "request header": "Anforderungsheader", 
   "Run Query": "Abfrage ausführen", 
   "request body": "Anforderungstext", 
   "Close": "Schließen", 
   "Getting Started": "Erste Schritte", 
   "Response": "Antwort", 
   "login to send requests": "Melden Sie an, um den Anforderungstyp zu ändern", 
   "Share Query": "Abfrage freigeben", 
   "Share this link to let people try your current query in the Graph Explorer.": "Teilen Sie diesen Link, damit Benutzer Ihre aktuelle Abfrage im Graph-Tester testen können.", 
   "Date": "Datum", 
 
 
   "my profile": "Eigenes Profil", 
   "my files": "meine Dateien", 
   "my photo": "mein Foto", 
   "my mail": "Eigene E-Mail", 
   "my manager": "Eigener Vorgesetzter", 
 
 
   "Response Headers": "Antwortheader", 
   "Response Preview": "Antwortvorschau", 
   "Sample Queries": "Beispielabfragen", 
 
 
   "show more groups": "Mehr Gruppen anzeigen", 
   "Sample Categories": "Beispielkategorien", 
 
 
   "On": "Ein", 
   "Off": "Off", 
   "Remove All": "Alle entfernen", 
 
 
   "Enter new header": "Neuen Header eingeben", 
 
 
   "Key": "Schlüssel", 
   "Value": "Wert", 
 
 
   "Login to try this request": "Melden Sie sich an, um diese Anforderung zu testen", 
 
 
   "modify permissions": "Berechtigungen ändern", 
   "Save changes": "Änderungen speichern", 
   "To change permissions, you will need to log-in again.": "Um Berechtigungen zu ändern, müssen Sie sich erneut anmelden.", 
 
 
   "all the items in my drive"	:"Alle Elemente in meinem Laufwerk", 
   "items trending around me"	:"Populäre Elemente", 
   "my direct reports"	:"Eigene Mitarbeiter", 
   "all users in the organization"	:"Alle Benutzer in der Organisation", 
   "all users in the Finance department"	:"Alle Benutzer in der Finanzabteilung", 
   "my skills"	:"Eigene Skills", 
   "all my Planner tasks"	:"Alle eigenen Planner-Aufgaben", 
   "track user changes"	:"Benutzeränderungen nachverfolgen", 
   "all groups in my organization"	:"Alle Benutzer in meiner Organisation", 
   "all groups I belong to"	:"Alle Gruppen, bei denen ich Mitglied bin", 
   "unified groups I belong to"	:"Einheitliche Gruppen, bei denen ich Mitglied bin", 
   "group members"	:"Gruppenmitglieder", 
   "group's conversations"	:"Gruppenunterhaltungen", 
   "group's events"	:"Gruppenereignisse", 
   "add favorite group"	:"Favoritengruppe hinzufügen", 
   "items in a group drive"	:"Elemente in einem Gruppenlaufwerk", 
   "track group changes"	:"Gruppenänderungen nachverfolgen", 
   "my high importance mail"	:"Eigene E-Mails mit Wichtigkeit „Hoch“", 
   "my mail that has 'Hello World'"	:"Eigene E-Mail, die „Hello World“ enthält", 
   "send an email"	:"E-Mail senden", 
   "forward mail"	:"E-Mail weiterleiten", 
   "track email changes"	:"E-Mail-Änderungen nachverfolgen", 
   "email I'm @ mentioned"	:"E-Mail, in der ich @-erwähnt werde", 
   "my events for the next week"	:"Eigene Ereignisse für die nächste Woche", 
   "all events in my calendar"	:"Alle Ereignisse im eigenen Kalender", 
   "all my calendars"	:"Alle eigenen Kalender", 
   "all my event reminders for next week"	:"Alle eigenen Ereigniserinnerungen für nächste Woche", 
   "find meeting time"	:"Besprechungszeit suchen", 
   "schedule a meeting"	:"Besprechung planen", 
   "track changes on my events for the next week"	:"Änderungen eigener Ereignisse für die nächste Woche nachverfolgen", 
   "my contacts"	:"Eigene Kontakte", 
   "add contact"	:"Kontakt hinzufügen", 
   "my recent files"	:"Eigene zuletzt verwendete Dateien", 
   "files shared with me"	:"Mit mir geteilte Dateien", 
   "all of my excel files"	:"Alle eigenen Excel-Dateien", 
   "create a folder"	:"Ordner erstellen", 
   "create session"	:"Sitzung erstellen", 
   "worksheets in a workbook"	:"Arbeitsblätter in einer Arbeitsmappe", 
   "add a new worksheet"	:"Neues Arbeitsblatt hinzufügen", 
   "used range in worksheet"	:"Im Arbeitsblatt verwendeter Bereich", 
   "tables in worksheet"	:"Tabellen im Arbeitsblatt", 
   "charts in worksheet"	:"Diagramme im Arbeitsblatt", 
   "all Planner plans associated with a group"	:"Alle einer Gruppe zugeordneten Planner-Pläne", 
   "all Planner tasks for a plan"	:"Alle Planner-Aufgaben für einen Plan", 
   "my organization's default SharePoint site"	:"SharePoint-Standardwebsite meiner Organisation", 
   "a SharePoint site by URL"	:"SharePoint-Website nach URL", 
   "subsites in a SharePoint site"	:"Unterwebsites einer SharePoint-Website", 
   "list in a SharePoint site "	:"Liste auf einer SharePoint-Website ", 
   "my notebooks"	:"Eigene Notizbücher", 
   "my sections"	:"Eigene Abschnitte", 
   "my pages"	:"Eigene Seiten", 
   "create notebook"	:"Notizbuch erstellen", 
   "create section"	:"Abschnitt erstellen", 
   "create page"	:"Seite erstellen", 
   "Users":"Benutzer", 
   "Users (preview)":"Benutzer (Vorschau)", 
   "Groups":"Gruppen", 
   "Groups (preview)":"Gruppen (Vorschau)", 
   "Outlook Mail":"Outlook-Mail", 
   "Outlook Mail (preview)":"Outlook-Mail (Vorschau)", 
   "Outlook Calendar":"Outlook-Kalender", 
   "Outlook Calendar (preview)":"Outlook-Kalender (Vorschau)", 
   "Personal Contacts":"Private Kontakte", 
   "OneDrive":"OneDrive", 
   "Excel":"Excel", 
   "Planner (beta)":"Planner (Beta)", 
   "SharePoint Sites (beta)":"SharePoint-Websites (Beta)", 
   "OneNote (beta)":"OneNote (Beta)", 
   "SharePoint Lists (beta)": "SharePoint-Listen (Beta)", 
   "Insights": "Insights", 
   "Insights (preview)": "Insights (Vorschau)" 
}


loc_strings['es-ES'] = {
  "To try the explorer, please ": "Para utilizar el probador,  ", 
   "sign in": "inicie sesión", 
   " with your work or school account from Microsoft.": " con su cuenta profesional o educativa de Microsoft.", 
   "Submit": "Enviar", 
   "Using demo tenant": "Actualmente está utilizando una cuenta de muestra.", 
   "To access your own data:": "Para tener acceso a sus propios datos:", 
   "sign out": "cerrar sesión", 
   "History": "Historial", 
   "Method": "Método", 
   "Query": "Consulta", 
   "Status Code": "Código de estado", 
   "Duration": "Duración", 
   "Go": "Ir", 
   "milliseconds": "ms", 
   "YES": "SÍ", 
   "Show More": "mostrar más", 
   "Graph Explorer": "Probador de Graph", 
   "Failure": "Erróneo", 
   "Success": "Correcto", 
   "Authentication": "Autenticación", 
   "NO": "NO", 
   "request header": "Encabezados de solicitud", 
   "Run Query": "Ejecutar consulta", 
   "request body": "Cuerpo de la solicitud", 
   "Close": "Cerrar", 
   "Getting Started": "Introducción", 
   "Response": "Respuesta", 
   "login to send requests": "Inicio de sesión para cambiar el tipo de solicitud", 
   "Share Query": "Compartir consulta", 
   "Share this link to let people try your current query in the Graph Explorer.": "Comparta este vínculo para permitir que la gente intente la consulta actual en el Probador de Graph.", 
   "Date": "Fecha", 
 
 
   "my profile": "mi perfil", 
   "my files": "mis archivos", 
   "my photo": "mi foto", 
   "my mail": "mi correo", 
   "my manager": "mi administrador", 
 
 
   "Response Headers": "Encabezados de respuesta", 
   "Response Preview": "Vista previa de la respuesta", 
   "Sample Queries": "Consultas de ejemplo", 
 
 
   "show more groups": "mostrar más grupos", 
   "Sample Categories": "Categorías de ejemplo", 
 
 
   "On": "Activado", 
   "Off": "Desactivado", 
   "Remove All": "Quitar todo", 
 
 
   "Enter new header": "Introducir encabezado nuevo", 
 
 
   "Key": "Clave", 
   "Value": "Valor", 
 
 
   "Login to try this request": "Inicie sesión para intentar esta solicitud", 
 
 
   "modify permissions": "modificar permisos", 
   "Save changes": "Guardar cambios", 
   "To change permissions, you will need to log-in again.": "Para cambiar los permisos, debe volver a iniciar sesión.", 
 
 
   "all the items in my drive"	:"todos los elementos de la unidad", 
   "items trending around me"	:"elementos populares de mi entorno", 
   "my direct reports"	:"mis informes directos", 
   "all users in the organization"	:"todos los usuarios de la organización", 
   "all users in the Finance department"	:"todos los usuarios del departamento de finanzas", 
   "my skills"	:"mis habilidades", 
   "all my Planner tasks"	:"todas mis tareas de Planner", 
   "track user changes"	:"hacer un seguimiento de los cambios de los usuarios", 
   "all groups in my organization"	:"todos los grupos de la organización", 
   "all groups I belong to"	:"todos los grupos a los que pertenezco", 
   "unified groups I belong to"	:"grupos unificados a los que pertenezco", 
   "group members"	:"miembros del grupo", 
   "group's conversations"	:"conversaciones del grupo", 
   "group's events"	:"eventos del grupo", 
   "add favorite group"	:"agregar grupo favorito", 
   "items in a group drive"	:"elementos de una unidad de grupo", 
   "track group changes"	:"hacer un seguimientos de los cambios en los grupos", 
   "my high importance mail"	:"mi correo electrónico de importancia alta", 
   "my mail that has 'Hello World'"	:"mi correo electrónico que contiene \"Hola a todos\"", 
   "send an email"	:"enviar un correo electrónico", 
   "forward mail"	:"reenviar correo electrónico", 
   "track email changes"	:"hacer un seguimiento de los cambios en el correo electrónico", 
   "email I'm @ mentioned"	:"correo electrónico en el que se me menciona", 
   "my events for the next week"	:"mis eventos para la próxima semana", 
   "all events in my calendar"	:"todos los eventos en mi calendario", 
   "all my calendars"	:"todos mis calendarios", 
   "all my event reminders for next week"	:"todos mis recordatorios de eventos para la próxima semana", 
   "find meeting time"	:"buscar horas de reunión", 
   "schedule a meeting"	:"programar una reunión", 
   "track changes on my events for the next week"	:"hacer un seguimiento de mis eventos para la próxima semana", 
   "my contacts"	:"mis contactos", 
   "add contact"	:"agregar contacto", 
   "my recent files"	:"mis archivos recientes", 
   "files shared with me"	:"archivos compartidos conmigo", 
   "all of my excel files"	:"todos mis archivos de Excel", 
   "create a folder"	:"crear una carpeta", 
   "create session"	:"crear una sesión", 
   "worksheets in a workbook"	:"hojas de cálculo de un libro", 
   "add a new worksheet"	:"agregar una hoja de cálculo nueva", 
   "used range in worksheet"	:"rango utilizado en una hoja de cálculo", 
   "tables in worksheet"	:"tablas en una hoja de cálculo", 
   "charts in worksheet"	:"gráficos en una hoja de cálculo", 
   "all Planner plans associated with a group"	:"todos los planes de Planner asociados a un grupo", 
   "all Planner tasks for a plan"	:"todas las tareas de Planner para un plan", 
   "my organization's default SharePoint site"	:"sitio de SharePoint predeterminado de mi organización", 
   "a SharePoint site by URL"	:"un sitio de SharePoint por la dirección URL", 
   "subsites in a SharePoint site"	:"subsitios de un sitio de SharePoint", 
   "list in a SharePoint site "	:"lista de un sitio de SharePoint ", 
   "my notebooks"	:"mis blocs de notas", 
   "my sections"	:"mis secciones", 
   "my pages"	:"mis páginas", 
   "create notebook"	:"crear bloc de notas", 
   "create section"	:"crear sección", 
   "create page"	:"crear página", 
   "Users":"Usuarios", 
   "Users (preview)":"Usuarios (versión preliminar)", 
   "Groups":"Grupos", 
   "Groups (preview)":"Grupos (versión preliminar)", 
   "Outlook Mail":"Correo de Outlook", 
   "Outlook Mail (preview)":"Correo de Outlook (versión preliminar)", 
   "Outlook Calendar":"Calendario de Outlook", 
   "Outlook Calendar (preview)":"Calendario de Outlook (versión preliminar)", 
   "Personal Contacts":"Contactos personales", 
   "OneDrive":"OneDrive", 
   "Excel":"Excel", 
   "Planner (beta)":"Planner (versión beta)", 
   "SharePoint Sites (beta)":"Sitios de SharePoint (versión beta)", 
   "OneNote (beta)":"OneNote (versión beta)", 
   "SharePoint Lists (beta)": "Listas de SharePoint (versión beta)", 
   "Insights": "Información", 
   "Insights (preview)": "Información (versión preliminar)" 
}


loc_strings['fr-FR'] = {
  "To try the explorer, please ": "Pour essayer l’afficheur, veuillez ", 
   "sign in": "vous connecter", 
   " with your work or school account from Microsoft.": " avec votre compte scolaire ou professionnel de Microsoft.", 
   "Submit": "Submit", 
   "Using demo tenant": "Vous utilisez actuellement un compte exemple.", 
   "To access your own data:": "Pour accéder à vos données :", 
   "sign out": "se déconnecter", 
   "History": "Historique", 
   "Method": "Méthode", 
   "Query": "Requête", 
   "Status Code": "Code d'état", 
   "Duration": "Durée", 
   "Go": "OK", 
   "milliseconds": "ms", 
   "YES": "OUI", 
   "Show More": "Plus", 
   "Graph Explorer": "Afficheur Graph", 
   "Failure": "Échec", 
   "Success": "Opération réussie", 
   "Authentication": "Authentification", 
   "NO": "NON", 
   "request header": "En-têtes de demande", 
   "Run Query": "Exécuter la requête", 
   "request body": "Corps de la requête", 
   "Close": "Fermer", 
   "Getting Started": "Mise en route", 
   "Response": "Réponse", 
   "login to send requests": "Connectez-vous pour modifier le type de requête", 
   "Share Query": "Partager la requête", 
   "Share this link to let people try your current query in the Graph Explorer.": "Partagez ce lien pour permettre aux utilisateurs d’essayer votre requête actuelle dans l’Afficheur Graph.", 
   "Date": "Date", 
 
 
   "my profile": "mon profil", 
   "my files": "mes fichiers", 
   "my photo": "ma photo", 
   "my mail": "mon courrier électronique", 
   "my manager": "mon responsable", 
 
 
   "Response Headers": "En-têtes de réponse", 
   "Response Preview": "Aperçu de la réponse", 
   "Sample Queries": "Exemples de requêtes", 
 
 
   "show more groups": "Plus de groupes", 
   "Sample Categories": "Exemples de catégories", 
 
 
   "On": "Activé", 
   "Off": "Désactivé", 
   "Remove All": "Supprimer tout", 
 
 
   "Enter new header": "Entrez le nouvel en-tête", 
 
 
   "Key": "Clé", 
   "Value": "Valeur", 
 
 
   "Login to try this request": "Connectez-vous pour tester cette demande", 
 
 
   "modify permissions": "modifier les autorisations", 
   "Save changes": "Enregistrer les modifications", 
   "To change permissions, you will need to log-in again.": "Pour modifier les autorisations, vous devez vous reconnecter.", 
 
 
   "all the items in my drive"	:"tous les éléments de mon lecteur", 
   "items trending around me"	:"éléments qui me sont suggérés", 
   "my direct reports"	:"mes collaborateurs directs", 
   "all users in the organization"	:"tous les utilisateurs de l’organisation", 
   "all users in the Finance department"	:"tous les utilisateurs du service financier", 
   "my skills"	:"mes compétences", 
   "all my Planner tasks"	:"toutes mes tâches du planificateur", 
   "track user changes"	:"suivre les modifications d’utilisateur", 
   "all groups in my organization"	:"tous les groupes de mon organisation", 
   "all groups I belong to"	:"tous les groupes auxquels j’appartiens", 
   "unified groups I belong to"	:"groupes unifiés auxquels j’appartiens", 
   "group members"	:"membres du groupe", 
   "group's conversations"	:"conversations du groupe", 
   "group's events"	:"événements du groupe", 
   "add favorite group"	:"ajouter un groupe favori", 
   "items in a group drive"	:"éléments d’un lecteur de groupe", 
   "track group changes"	:"suivre les modifications de groupe", 
   "my high importance mail"	:"mon courrier électronique de haute importance", 
   "my mail that has 'Hello World'"	:"mon courrier contenant « Hello World »", 
   "send an email"	:"envoyer un courrier", 
   "forward mail"	:"transférer un courrier", 
   "track email changes"	:"suivre les modifications de courrier", 
   "email I'm @ mentioned"	:"courrier où je suis mentionné", 
   "my events for the next week"	:"mes événements pour la semaine prochaine", 
   "all events in my calendar"	:"tous les événements de mon calendrier", 
   "all my calendars"	:"tous mes calendriers", 
   "all my event reminders for next week"	:"tous mes rappels d’événement pour la semaine prochaine", 
   "find meeting time"	:"rechercher l’heure de la réunion", 
   "schedule a meeting"	:"planifier une réunion", 
   "track changes on my events for the next week"	:"suivre les modifications de mes événements de la semaine prochaine", 
   "my contacts"	:"mes contacts", 
   "add contact"	:"ajouter un contact", 
   "my recent files"	:"mes fichiers récents", 
   "files shared with me"	:"fichiers partagés avec moi", 
   "all of my excel files"	:"tous mes fichiers excel", 
   "create a folder"	:"créer un dossier", 
   "create session"	:"créer une session", 
   "worksheets in a workbook"	:"feuilles de calcul d’un classeur", 
   "add a new worksheet"	:"ajouter une nouvelle feuille de calcul", 
   "used range in worksheet"	:"plage utilisée dans la feuille de calcul", 
   "tables in worksheet"	:"tableaux dans la feuille de calcul", 
   "charts in worksheet"	:"graphiques dans la feuille de calcul", 
   "all Planner plans associated with a group"	:"tous les plans du planificateur associés à un groupe", 
   "all Planner tasks for a plan"	:"toutes les tâches de planificateur d’un plan", 
   "my organization's default SharePoint site"	:"site SharePoint par défaut de mon organisation", 
   "a SharePoint site by URL"	:"site SharePoint par URL", 
   "subsites in a SharePoint site"	:"sous-sites dans un site SharePoint", 
   "list in a SharePoint site "	:"liste dans un site SharePoint ", 
   "my notebooks"	:"mes blocs-notes", 
   "my sections"	:"mes sections", 
   "my pages"	:"mes pages", 
   "create notebook"	:"créer un bloc-notes", 
   "create section"	:"créer une section", 
   "create page"	:"créer une page", 
   "Users":"Utilisateurs", 
   "Users (preview)":"Utilisateurs (aperçu)", 
   "Groups":"Groupes", 
   "Groups (preview)":"Groupes (aperçu)", 
   "Outlook Mail":"Messagerie Outlook", 
   "Outlook Mail (preview)":"Messagerie Outlook (aperçu)", 
   "Outlook Calendar":"Calendrier Outlook", 
   "Outlook Calendar (preview)":"Calendrier Outlook (aperçu)", 
   "Personal Contacts":"Contacts personnels", 
   "OneDrive":"OneDrive", 
   "Excel":"Excel", 
   "Planner (beta)":"Planificateur (bêta)", 
   "SharePoint Sites (beta)":"Sites SharePoint (bêta)", 
   "OneNote (beta)":"OneNote (bêta)", 
   "SharePoint Lists (beta)": "Listes SharePoint (bêta)", 
   "Insights": "Connaissances", 
   "Insights (preview)": "Insights (aperçu)" 
}


loc_strings['ja-JP'] = {
  "To try the explorer, please ": "エクスプローラーをお試しいただくには、Microsoft の職場または学校アカウントで ", 
   "sign in": "サインイン", 
   " with your work or school account from Microsoft.": " します。", 
   "Submit": "送信", 
   "Using demo tenant": "現在、サンプル アカウントを使用しています。", 
   "To access your own data:": "自分のデータにアクセスするには:", 
   "sign out": "サインアウト", 
   "History": "履歴", 
   "Method": "メソッド", 
   "Query": "クエリ", 
   "Status Code": "状態コード", 
   "Duration": "期間", 
   "Go": "実行", 
   "milliseconds": "ミリ秒", 
   "YES": "はい", 
   "Show More": "さらに表示", 
   "Graph Explorer": "Graph エクスプローラー", 
   "Failure": "失敗", 
   "Success": "成功", 
   "Authentication": "認証", 
   "NO": "いいえ", 
   "request header": "要求ヘッダー", 
   "Run Query": "クエリを実行", 
   "request body": "要求本文", 
   "Close": "閉じる", 
   "Getting Started": "はじめに", 
   "Response": "応答", 
   "login to send requests": "要求の種類を変更するにはログインしてください", 
   "Share Query": "クエリの共有", 
   "Share this link to let people try your current query in the Graph Explorer.": "他のユーザーが Graph エクスプローラーで現在のクエリを試せるようにするには、このリンクを共有してください。", 
   "Date": "日付", 
 
 
   "my profile": "自分のプロファイル", 
   "my files": "自分のファイル", 
   "my photo": "自分の写真", 
   "my mail": "自分のメール", 
   "my manager": "自分の上司", 
 
 
   "Response Headers": "応答ヘッダー", 
   "Response Preview": "応答のプレビュー", 
   "Sample Queries": "サンプル クエリ", 
 
 
   "show more groups": "その他のグループを表示", 
   "Sample Categories": "サンプル カテゴリ", 
 
 
   "On": "オン", 
   "Off": "オフ", 
   "Remove All": "すべて削除", 
 
 
   "Enter new header": "新しいヘッダーを入力", 
 
 
   "Key": "キー", 
   "Value": "値", 
 
 
   "Login to try this request": "ログインしてこの要求を試す", 
 
 
   "modify permissions": "アクセス許可の修正", 
   "Save changes": "変更の保存", 
   "To change permissions, you will need to log-in again.": "アクセス許可を変更するには、もう一度ログインする必要があります。", 
 
 
   "all the items in my drive"	:"自分のドライブ内のすべての項目", 
   "items trending around me"	:"自分の周りで人気上昇中の項目", 
   "my direct reports"	:"自分の直属の部下", 
   "all users in the organization"	:"組織内のすべてのユーザー", 
   "all users in the Finance department"	:"財務部門のすべてのユーザー", 
   "my skills"	:"自分のスキル", 
   "all my Planner tasks"	:"自分のすべてのプランナー タスク", 
   "track user changes"	:"ユーザー変更の追跡", 
   "all groups in my organization"	:"自分の組織内のすべてのグループ", 
   "all groups I belong to"	:"自分の所属するすべてのグループ", 
   "unified groups I belong to"	:"自分の所属する統合グループ", 
   "group members"	:"グループ メンバー", 
   "group's conversations"	:"グループの会話", 
   "group's events"	:"グループのイベント", 
   "add favorite group"	:"お気に入りのグループを追加する", 
   "items in a group drive"	:"グループ ドライブ内の項目", 
   "track group changes"	:"グループ変更の追跡", 
   "my high importance mail"	:"重要度の高い自分のメール", 
   "my mail that has 'Hello World'"	:"'Hello World' を含む自分のメール", 
   "send an email"	:"電子メールを送信する", 
   "forward mail"	:"電子メールを転送する", 
   "track email changes"	:"電子メール変更の追跡", 
   "email I'm @ mentioned"	:"自分が @ メンションされている電子メール", 
   "my events for the next week"	:"来週の自分の予定", 
   "all events in my calendar"	:"自分の予定表のすべての予定", 
   "all my calendars"	:"自分のすべての予定表", 
   "all my event reminders for next week"	:"来週の自分のすべての予定のアラーム", 
   "find meeting time"	:"会議の日時を検索する", 
   "schedule a meeting"	:"会議の予約", 
   "track changes on my events for the next week"	:"来週の自分の予定の変更の追跡", 
   "my contacts"	:"連絡先", 
   "add contact"	:"連絡先を追加する", 
   "my recent files"	:"最近使ったファイル", 
   "files shared with me"	:"自分と共有したファイル", 
   "all of my excel files"	:"自分のすべての Excel ファイル", 
   "create a folder"	:"フォルダーを作成する", 
   "create session"	:"セッションを作成する", 
   "worksheets in a workbook"	:"ブック内のワークシート", 
   "add a new worksheet"	:"新しいワークシートを追加する", 
   "used range in worksheet"	:"ワークシートの使用範囲", 
   "tables in worksheet"	:"ワークシートのテーブル", 
   "charts in worksheet"	:"ワークシートのグラフ", 
   "all Planner plans associated with a group"	:"グループに関連付けられているすべてのプランナーの計画", 
   "all Planner tasks for a plan"	:"計画のすべてのプランナー タスク", 
   "my organization's default SharePoint site"	:"自分の組織の既定の SharePoint サイト", 
   "a SharePoint site by URL"	:"URL ごとの SharePoint サイト", 
   "subsites in a SharePoint site"	:"SharePoint サイト内のサブサイト", 
   "list in a SharePoint site "	:"SharePoint サイト内のリスト ", 
   "my notebooks"	:"自分のノートブック", 
   "my sections"	:"自分のセクション", 
   "my pages"	:"自分のページ", 
   "create notebook"	:"ノートブックを作成する", 
   "create section"	:"セクションを作成する", 
   "create page"	:"ページを作成する", 
   "Users":"ユーザー", 
   "Users (preview)":"ユーザー (プレビュー)", 
   "Groups":"グループ", 
   "Groups (preview)":"グループ (プレビュー)", 
   "Outlook Mail":"Outlook メール", 
   "Outlook Mail (preview)":"Outlook メール (プレビュー)", 
   "Outlook Calendar":"Outlook カレンダー", 
   "Outlook Calendar (preview)":"Outlook カレンダー (プレビュー)", 
   "Personal Contacts":"個人用連絡先", 
   "OneDrive":"OneDrive", 
   "Excel":"Excel", 
   "Planner (beta)":"Planner (ベータ版)", 
   "SharePoint Sites (beta)":"SharePoint サイト (ベータ版)", 
   "OneNote (beta)":"OneNote (ベータ版)", 
   "SharePoint Lists (beta)": "SharePoint リスト (ベータ版)", 
   "Insights": "Insights", 
   "Insights (preview)": "Insights (プレビュー)" 
}


loc_strings['zh-CN'] = {
  "To try the explorer, please ": "若要尝试使用资源管理器，请若要尝试浏览器，请 使用你的 Microsoft 工作或学校帐户 ", 
   "sign in": "登录", 
   " with your work or school account from Microsoft.": " 使用 Microsoft 提供的工作或学校帐户。", 
   "Submit": "提交", 
   "Using demo tenant": "当前使用的是示例帐户。", 
   "To access your own data:": "若要访问你自己的数据:", 
   "sign out": "注销", 
   "History": "历史记录", 
   "Method": "方法", 
   "Query": "查询", 
   "Status Code": "状态代码", 
   "Duration": "持续时间", 
   "Go": "调用", 
   "milliseconds": "毫秒", 
   "YES": "是", 
   "Show More": "显示更多", 
   "Graph Explorer": "Graph 浏览器", 
   "Failure": "失败", 
   "Success": "成功", 
   "Authentication": "身份验证", 
   "NO": "否", 
   "request header": "请求头", 
   "Run Query": "运行查询", 
   "request body": "请求正文", 
   "Close": "关闭", 
   "Getting Started": "开始使用", 
   "Response": "响应", 
   "login to send requests": "登录以更改请求类型", 
   "Share Query": "共享查询", 
   "Share this link to let people try your current query in the Graph Explorer.": "共享此链接可让其他人在 Graph 浏览器中尝试执行当前查询。", 
   "Date": "日期", 
 
 
   "my profile": "我的个人资料", 
   "my files": "我的文件", 
   "my photo": "我的照片", 
   "my mail": "我的邮件", 
   "my manager": "我的经理", 
 
 
   "Response Headers": "响应标头", 
   "Response Preview": "响应预览", 
   "Sample Queries": "示例查询", 
 
 
   "show more groups": "显示更多组", 
   "Sample Categories": "示例类别", 
 
 
   "On": "打开", 
   "Off": "关闭", 
   "Remove All": "全部删除", 
 
 
   "Enter new header": "输入新标头", 
 
 
   "Key": "键", 
   "Value": "值", 
 
 
   "Login to try this request": "登录以尝试此请求", 
 
 
   "modify permissions": "修改权限", 
   "Save changes": "保存更改", 
   "To change permissions, you will need to log-in again.": "若要更改权限，必须重新登录。", 
 
 
   "all the items in my drive"	:"我的驱动器中的所有项", 
   "items trending around me"	:"我常用的项目", 
   "my direct reports"	:"我的直接下属", 
   "all users in the organization"	:"组织中的所有用户", 
   "all users in the Finance department"	:"财务部门中的所有用户", 
   "my skills"	:"我的技能", 
   "all my Planner tasks"	:"我的所有规划器任务", 
   "track user changes"	:"跟踪用户更改", 
   "all groups in my organization"	:"我的组织中的所有组", 
   "all groups I belong to"	:"我所属的全部组", 
   "unified groups I belong to"	:"我所属的统一组", 
   "group members"	:"组成员", 
   "group's conversations"	:"组对话", 
   "group's events"	:"组事件", 
   "add favorite group"	:"添加收藏夹组", 
   "items in a group drive"	:"组驱动器中的项", 
   "track group changes"	:"跟踪组更改", 
   "my high importance mail"	:"我的高重要性邮件", 
   "my mail that has 'Hello World'"	:"我的包含 “Hello World” 的邮件", 
   "send an email"	:"发送电子邮件", 
   "forward mail"	:"转发邮件", 
   "track email changes"	:"跟踪电子邮件更改", 
   "email I'm @ mentioned"	:"提及的我 @ 的电子邮件", 
   "my events for the next week"	:"我的下周事件", 
   "all events in my calendar"	:"我的日历中的所有事件", 
   "all my calendars"	:"我的所有日历", 
   "all my event reminders for next week"	:"我下周的所有事件提醒", 
   "find meeting time"	:"查找会议时间", 
   "schedule a meeting"	:"安排会议", 
   "track changes on my events for the next week"	:"跟踪我的下周事件更改", 
   "my contacts"	:"我的联系人", 
   "add contact"	:"添加联系人", 
   "my recent files"	:"我最近使用的文件", 
   "files shared with me"	:"与我共享的文件", 
   "all of my excel files"	:"我的所有 excel 文件", 
   "create a folder"	:"创建文件夹", 
   "create session"	:"创建会话", 
   "worksheets in a workbook"	:"工作簿中的工作表", 
   "add a new worksheet"	:"添加新的工作表", 
   "used range in worksheet"	:"工作表中的使用区域", 
   "tables in worksheet"	:"工作表中的表", 
   "charts in worksheet"	:"工作表中的图表", 
   "all Planner plans associated with a group"	:"与组关联的所有规划器计划", 
   "all Planner tasks for a plan"	:"计划的所有规划器任务", 
   "my organization's default SharePoint site"	:"我的组织的默认 SharePoint 网站", 
   "a SharePoint site by URL"	:"SharePoint 网站(通过 URL)", 
   "subsites in a SharePoint site"	:"SharePoint 网站中的子网站", 
   "list in a SharePoint site "	:"SharePoint 网站中的列表 ", 
   "my notebooks"	:"我的笔记本", 
   "my sections"	:"我的分区", 
   "my pages"	:"我的页面", 
   "create notebook"	:"创建笔记本", 
   "create section"	:"创建分区", 
   "create page"	:"创建页面", 
   "Users":"用户", 
   "Users (preview)":"用户(预览)", 
   "Groups":"组", 
   "Groups (preview)":"组(预览)", 
   "Outlook Mail":"Outlook 邮件", 
   "Outlook Mail (preview)":"Outlook 邮件(预览)", 
   "Outlook Calendar":"Outlook 日历", 
   "Outlook Calendar (preview)":"Outlook 日历(预览)", 
   "Personal Contacts":"个人联系人", 
   "OneDrive":"OneDrive", 
   "Excel":"Excel", 
   "Planner (beta)":"规划器 (beta)", 
   "SharePoint Sites (beta)":"SharePoint 网站 (beta)", 
   "OneNote (beta)":"OneNote (beta)", 
   "SharePoint Lists (beta)": "SharePoint 列表 (beta)", 
   "Insights": "见解", 
   "Insights (preview)": "见解(预览)" 
}


loc_strings['pt-BR'] = {
  "To try the explorer, please ": "Para experimentar o Explorador, ", 
   "sign in": "entre", 
   " with your work or school account from Microsoft.": " com a sua conta corporativa ou de estudante da Microsoft.", 
   "Submit": "Enviar", 
   "Using demo tenant": "No momento, você está usando uma conta de exemplo.", 
   "To access your own data:": "Para acessar seus dados:", 
   "sign out": "sair", 
   "History": "Histórico", 
   "Method": "Método", 
   "Query": "Consulta", 
   "Status Code": "Código de Status", 
   "Duration": "Duração", 
   "Go": "Ir", 
   "milliseconds": "ms", 
   "YES": "SIM", 
   "Show More": "mostrar mais", 
   "Graph Explorer": "Explorador do Graph", 
   "Failure": "Falha", 
   "Success": "Êxito", 
   "Authentication": "Autenticação", 
   "NO": "NÃO", 
   "request header": "Cabeçalhos de solicitação", 
   "Run Query": "Executar Consulta", 
   "request body": "Corpo da Solicitação", 
   "Close": "Fechar", 
   "Getting Started": "Introdução", 
   "Response": "Resposta", 
   "login to send requests": "Entre para alterar o tipo de solicitação", 
   "Share Query": "Compartilhar Consulta", 
   "Share this link to let people try your current query in the Graph Explorer.": "Compartilhe este link para que as pessoas possam experimentar a consulta atual no Explorador do Graph.", 
   "Date": "Data", 
 
 
   "my profile": "meu perfil", 
   "my files": "meus arquivos", 
   "my photo": "minha foto", 
   "my mail": "meu email", 
   "my manager": "meu gerente", 
 
 
   "Response Headers": "Cabeçalhos da Resposta", 
   "Response Preview": "Visualização da Resposta", 
   "Sample Queries": "Consultas de Exemplo", 
 
 
   "show more groups": "mostrar mais grupos", 
   "Sample Categories": "Categorias de Exemplo", 
 
 
   "On": "Habilitado", 
   "Off": "Desabilitado", 
   "Remove All": "Remover Tudo", 
 
 
   "Enter new header": "Inserir novo cabeçalho", 
 
 
   "Key": "Chave", 
   "Value": "Valor", 
 
 
   "Login to try this request": "Entre para testar esta solicitação", 
 
 
   "modify permissions": "modificar permissões", 
   "Save changes": "Salvar alterações", 
   "To change permissions, you will need to log-in again.": "Para alterar permissões, entre novamente.", 
 
 
   "all the items in my drive"	:"todos os itens da minha unidade", 
   "items trending around me"	:"itens mais populares à minha volta", 
   "my direct reports"	:"meus subordinados diretos", 
   "all users in the organization"	:"todos os usuários da organização", 
   "all users in the Finance department"	:"todos os usuários do departamento financeiro", 
   "my skills"	:"minhas habilidades", 
   "all my Planner tasks"	:"todas as minhas tarefas do Planner", 
   "track user changes"	:"controlar alterações do usuário", 
   "all groups in my organization"	:"todos os grupos em minha organização", 
   "all groups I belong to"	:"todos os grupos aos quais pertenço", 
   "unified groups I belong to"	:"grupos unificados aos quais pertenço", 
   "group members"	:"membros do grupo", 
   "group's conversations"	:"conversas do grupo", 
   "group's events"	:"eventos do grupo", 
   "add favorite group"	:"adicionar grupo favorito", 
   "items in a group drive"	:"itens de uma unidade de grupo", 
   "track group changes"	:"controlar alterações do grupo", 
   "my high importance mail"	:"meu email de alta prioridade", 
   "my mail that has 'Hello World'"	:"meu email que tenha 'Hello World'", 
   "send an email"	:"enviar um email", 
   "forward mail"	:"encaminhar email", 
   "track email changes"	:"controlar alterações de email", 
   "email I'm @ mentioned"	:"email no qual sou @ mencionado", 
   "my events for the next week"	:"meus eventos para a próxima semana", 
   "all events in my calendar"	:"todos os eventos do meu calendário", 
   "all my calendars"	:"todos os meus calendários", 
   "all my event reminders for next week"	:"todos os meus lembretes de eventos para a próxima semana", 
   "find meeting time"	:"encontrar horário da reunião", 
   "schedule a meeting"	:"agendar uma reunião", 
   "track changes on my events for the next week"	:"controlar alterações em meus eventos para a próxima semana", 
   "my contacts"	:"meus contatos", 
   "add contact"	:"adicionar contato", 
   "my recent files"	:"meus arquivos recentes", 
   "files shared with me"	:"arquivos compartilhados comigo", 
   "all of my excel files"	:"todos os meus arquivos do Excel", 
   "create a folder"	:"criar uma pasta", 
   "create session"	:"criar sessão", 
   "worksheets in a workbook"	:"planilhas em uma pasta de trabalho", 
   "add a new worksheet"	:"adicionar uma nova planilha", 
   "used range in worksheet"	:"intervalo usado em uma planilha", 
   "tables in worksheet"	:"tabelas da planilha", 
   "charts in worksheet"	:"gráficos da planilha", 
   "all Planner plans associated with a group"	:"todos os planos do Planner associados a um grupo", 
   "all Planner tasks for a plan"	:"todas as tarefas do Planner para um plano", 
   "my organization's default SharePoint site"	:"site padrão do SharePoint da minha organização", 
   "a SharePoint site by URL"	:"um site do SharePoint pela URL", 
   "subsites in a SharePoint site"	:"subsites de um site do SharePoint", 
   "list in a SharePoint site "	:"lista em um site do SharePoint ", 
   "my notebooks"	:"meus blocos de anotações", 
   "my sections"	:"minhas seções", 
   "my pages"	:"minhas páginas", 
   "create notebook"	:"criar bloco de anotações", 
   "create section"	:"criar seção", 
   "create page"	:"criar página", 
   "Users":"Usuários", 
   "Users (preview)":"Usuários (visualização)", 
   "Groups":"Grupos", 
   "Groups (preview)":"Grupos (visualização)", 
   "Outlook Mail":"Email do Outlook", 
   "Outlook Mail (preview)":"Email do Outlook (visualização)", 
   "Outlook Calendar":"Calendário do Outlook", 
   "Outlook Calendar (preview)":"Calendário do Outlook (visualização)", 
   "Personal Contacts":"Contatos Pessoais", 
   "OneDrive":"OneDrive", 
   "Excel":"Excel", 
   "Planner (beta)":"Planner (beta)", 
   "SharePoint Sites (beta)":"Sites do SharePoint (beta)", 
   "OneNote (beta)":"OneNote (beta)", 
   "SharePoint Lists (beta)": "Listas do SharePoint (beta)", 
   "Insights": "Insights", 
   "Insights (preview)": "Insights (visualização)" 
}


loc_strings['ru-RU'] = {
  "To try the explorer, please ": "Чтобы опробовать песочницу, ", 
   "sign in": "войдите", 
   " with your work or school account from Microsoft.": " с помощью рабочей или учебной учетной записи от корпорации Майкрософт.", 
   "Submit": "Отправить", 
   "Using demo tenant": "В настоящее время вы используете пример учетной записи.", 
   "To access your own data:": "Для доступа к собственным данным:", 
   "sign out": "выйти", 
   "History": "Журнал", 
   "Method": "Метод", 
   "Query": "Запрос", 
   "Status Code": "Код состояния", 
   "Duration": "Срок действия", 
   "Go": "Переход", 
   "milliseconds": "ms", 
   "YES": "ДА", 
   "Show More": "показать еще", 
   "Graph Explorer": "Песочница Graph", 
   "Failure": "Ошибка", 
   "Success": "Успешно", 
   "Authentication": "Проверка подлинности", 
   "NO": "НЕТ", 
   "request header": "Заголовки запросов", 
   "Run Query": "Выполнить запрос", 
   "request body": "Текст запроса", 
   "Close": "Закрыть", 
   "Getting Started": "Начало работы", 
   "Response": "Отклик", 
   "login to send requests": "Войдите, чтобы изменить тип запроса", 
   "Share Query": "Поделиться запросом", 
   "Share this link to let people try your current query in the Graph Explorer.": "Поделитесь этой ссылкой, чтобы другие пользователи могли попробовать ваш текущий запрос в песочнице Graph.", 
   "Date": "Дата", 
 
 
   "my profile": "мой профиль", 
   "my files": "мои файлы", 
   "my photo": "мои фото", 
   "my mail": "моя почта", 
   "my manager": "мой руководитель", 
 
 
   "Response Headers": "Заголовки ответа", 
   "Response Preview": "Предварительный просмотр ответа", 
   "Sample Queries": "Примеры запросов", 
 
 
   "show more groups": "показать еще группы", 
   "Sample Categories": "Примеры категорий", 
 
 
   "On": "Вкл.", 
   "Off": "Выкл.", 
   "Remove All": "Удалить все", 
 
 
   "Enter new header": "Введите новый заголовок", 
 
 
   "Key": "Ключ", 
   "Value": "Значение", 
 
 
   "Login to try this request": "Войдите, чтобы выполнить этот запрос", 
 
 
   "modify permissions": "изменить разрешения", 
   "Save changes": "Сохранить изменения", 
   "To change permissions, you will need to log-in again.": "Чтобы изменить разрешения, необходимо войти еще раз.", 
 
 
   "all the items in my drive"	:"все элементы на моем диске", 
   "items trending around me"	:"элементы, популярные в вашей компании", 
   "my direct reports"	:"мои подчиненные", 
   "all users in the organization"	:"все пользователи в организации", 
   "all users in the Finance department"	:"все пользователи в отделе финансов", 
   "my skills"	:"мои навыки", 
   "all my Planner tasks"	:"все мои задачи в Планировщике", 
   "track user changes"	:"отслеживание изменений пользователей", 
   "all groups in my organization"	:"все группы в моей организации", 
   "all groups I belong to"	:"все группы, в которые я вхожу", 
   "unified groups I belong to"	:"объединенные группы, в которые я вхожу", 
   "group members"	:"участники группы", 
   "group's conversations"	:"беседы группы", 
   "group's events"	:"события группы", 
   "add favorite group"	:"добавить любимую группу", 
   "items in a group drive"	:"элементы на диске группы", 
   "track group changes"	:"отслеживание изменений в группах", 
   "my high importance mail"	:"моя почта высокой важности", 
   "my mail that has 'Hello World'"	:"моя почта с фразой Hello World", 
   "send an email"	:"отправить сообщение", 
   "forward mail"	:"переслать сообщение", 
   "track email changes"	:"отслеживание изменений в электронной почте", 
   "email I'm @ mentioned"	:"сообщения, в которых меня упомянули @", 
   "my events for the next week"	:"мои события на следующей неделе", 
   "all events in my calendar"	:"все события в моем календаре", 
   "all my calendars"	:"все мои календари", 
   "all my event reminders for next week"	:"все напоминания о моих событиях на следующей неделе", 
   "find meeting time"	:"найти время для собрания", 
   "schedule a meeting"	:"запланировать собрание", 
   "track changes on my events for the next week"	:"отслеживание изменений в моих событиях на следующей неделе", 
   "my contacts"	:"мои контакты", 
   "add contact"	:"добавить контакт", 
   "my recent files"	:"мои последние файлы", 
   "files shared with me"	:"файлы, к которым мне предоставлен доступ", 
   "all of my excel files"	:"все мои файлы excel", 
   "create a folder"	:"создать папку", 
   "create session"	:"создать сеанс", 
   "worksheets in a workbook"	:"листы в книге", 
   "add a new worksheet"	:"добавить лист", 
   "used range in worksheet"	:"используемый диапазон на листе", 
   "tables in worksheet"	:"таблицы на листе", 
   "charts in worksheet"	:"диаграммы на листе", 
   "all Planner plans associated with a group"	:"все планы в Планировщике, связанные с группой", 
   "all Planner tasks for a plan"	:"все задачи в Планировщик, связанные с планом", 
   "my organization's default SharePoint site"	:"сайт SharePoint по умолчанию для моей организации", 
   "a SharePoint site by URL"	:"сайт SharePoint по URL-адресу", 
   "subsites in a SharePoint site"	:"дочерние сайты на сайте SharePoint", 
   "list in a SharePoint site "	:"список на сайте SharePoint ", 
   "my notebooks"	:"мои записные книжки", 
   "my sections"	:"мои разделы", 
   "my pages"	:"мои страницы", 
   "create notebook"	:"создать записную книжку", 
   "create section"	:"создать раздел", 
   "create page"	:"создать страницу", 
   "Users":"Пользователи", 
   "Users (preview)":"Пользователи (предварительная версия)", 
   "Groups":"Группы", 
   "Groups (preview)":"Группы (предварительная версия)", 
   "Outlook Mail":"Почта Outlook", 
   "Outlook Mail (preview)":"Почта Outlook (предварительная версия)", 
   "Outlook Calendar":"Календарь Outlook", 
   "Outlook Calendar (preview)":"Календарь Outlook (предварительная версия)", 
   "Personal Contacts":"Личные контакты", 
   "OneDrive":"OneDrive", 
   "Excel":"Excel", 
   "Planner (beta)":"Планировщик (бета-версия)", 
   "SharePoint Sites (beta)":"Сайты SharePoint (бета-версия)", 
   "OneNote (beta)":"OneNote (бета-версия)", 
   "SharePoint Lists (beta)": "Списки SharePoint (бета-версия)", 
   "Insights": "Insights", 
   "Insights (preview)": "Insights (предварительная версия)" 
}
