// This is a generated file from bundleLocFiles.js 

export const loc_strings = {};

loc_strings['de-DE'] = {
  "To try the explorer, please ": "Um den Tester auszuprobieren, ",
  "sign in": "melden Sie sich",
  " with your work or school account from Microsoft.": " mit Ihrem Geschäfts-, Schul- oder Unikonto von Microsoft an.",
  "Submit": "Senden",
  "Using demo tenant": "Sie verwenden derzeit ein Beispielkonto.",
  "To access your own data:": "So greifen Sie auf Ihre eigenen Daten zu:",
  "sign out": "Abmelden",
  "History": "Verlauf",
  "Method": "Methode",
  "Query": "Abfrage",
  "Status Code": "Statuscode",
  "Duration": "Dauer",
  "Go": "Gehe zu",
  "milliseconds": "ms",
  "YES": "JA",
  "Show More": "Mehr anzeigen",
  "Graph Explorer": "Graph-Tester",
  "Failure": "Misserfolg",
  "Success": "Erfolg",
  "Authentication": "Authentifizierung",
  "NO": "NEIN",
  "request header": "Anforderungsheader",
  "Run Query": "Abfrage ausführen",
  "request body": "Anforderungstext",
  "Close": "Schließen",
  "Getting Started": "Erste Schritte",
  "Response": "Antwort",
  "login to send requests": "Melden Sie an, um den Anforderungstyp zu ändern",
  "Share Query": "Abfrage freigeben",
  "Share this link to let people try your current query in the Graph Explorer.": "Teilen Sie diesen Link, damit Benutzer Ihre aktuelle Abfrage im Graph-Tester testen können.",

  "my profile": "mein Profil",
  "my files": "meine Dateien",
  "my photo": "mein Foto",
  "my mail": "meine E-Mail",
  "my high importance mail": "meine E-Mail mit hoher Wichtigkeit",
  "my calendar": "mein Kalender",
  "my manager": "mein Manager"
}


loc_strings['fr-FR'] = {
  "To try the explorer, please ": "Pour essayer l’afficheur, veuillez ",
  "sign in": "vous connecter",
  " with your work or school account from Microsoft.": " avec votre compte scolaire ou professionnel de Microsoft.",
  "Submit": "Submit",
  "Using demo tenant": "Vous utilisez actuellement un compte exemple.",
  "To access your own data:": "Pour accéder à vos données :",
  "sign out": "Se déconnecter",
  "History": "Historique",
  "Method": "Méthode",
  "Query": "Requête",
  "Status Code": "Code d'état",
  "Duration": "Durée",
  "Go": "OK",
  "milliseconds": "ms",
  "YES": "OUI",
  "Show More": "Afficher plus",
  "Graph Explorer": "Afficheur Graph",
  "Failure": "Échec",
  "Success": "Opération réussie",
  "Authentication": "Authentification",
  "NO": "NON",
  "request header": "En-têtes de demande",
  "Run Query": "Exécuter la requête",
  "request body": "Corps de la requête",
  "Close": "Fermer",
  "Getting Started": "Mise en route",
  "Response": "Réponse",
  "login to send requests": "Connectez-vous pour modifier le type de requête",
  "Share Query": "Partager la requête",
  "Share this link to let people try your current query in the Graph Explorer.": "Partagez ce lien pour permettre aux utilisateurs d’essayer votre requête actuelle dans l’Afficheur Graph.",

  "my profile": "mon profil",
  "my files": "mes fichiers",
  "my photo": "ma photo",
  "my mail": "mon courrier électronique",
  "my high importance mail": "mon courrier électronique de haute importance",
  "my calendar": "mon calendrier",
  "my manager": "mon responsable"
}


loc_strings['ru-RU'] = ﻿{
  "To try the explorer, please ": "Чтобы опробовать песочницу, ",
  "sign in": "войдите",
  " with your work or school account from Microsoft.": " с помощью рабочей или учебной учетной записи от корпорации Майкрософт.",
  "Submit": "Отправить",
  "Using demo tenant": "В настоящее время вы используете пример учетной записи.",
  "To access your own data:": "Для доступа к собственным данным:",
  "sign out": "Выход",
  "History": "Журнал",
  "Method": "Метод",
  "Query": "Запрос",
  "Status Code": "Код состояния",
  "Duration": "Срок действия",
  "Go": "Переход",
  "milliseconds": "мс",
  "YES": "ДА",
  "Show More": "Больше",
  "Graph Explorer": "Песочница Graph",
  "Failure": "Ошибка",
  "Success": "Успешно",
  "Authentication": "Проверка подлинности",
  "NO": "НЕТ",
  "request header": "Заголовки запросов",
  "Run Query": "Выполнить запрос",
  "request body": "Текст запроса",
  "Close": "Закрыть",
  "Getting Started": "Начало работы",
  "Response": "Отклик",
  "login to send requests": "Войдите, чтобы изменить тип запроса",
  "Share Query": "Поделиться запросом",
  "Share this link to let people try your current query in the Graph Explorer.": "Поделитесь этой ссылкой, чтобы другие пользователи могли попробовать ваш текущий запрос в песочнице Graph.",

  "my profile": "мой профиль",
  "my files": "мои файлы",
  "my photo": "мои фото",
  "my mail": "моя почта",
  "my high importance mail": "моя почта высокой важности",
  "my calendar": "мой календарь",
  "my manager": "мой руководитель"
}

loc_strings['en-US'] = {
  "To try the explorer, please ": "To try the explorer, please ",
  "sign in": "sign in",
  " with your work or school account from Microsoft.": " with your work or school account from Microsoft.",
  "Submit": "Submit",
  "Using demo tenant": "You are currently using a sample account.",
  "To access your own data:": "To access your own data:",
  "sign out": "sign out",
  "History": "History",
  "Method": "Method",
  "Query": "Query",
  "Status Code": "Status Code",
  "Duration": "Duration",
  "Go": "Go",
  "milliseconds": "ms",
  "YES": "YES",
  "Show More": "show more",
  "Graph Explorer": "Graph Explorer",
  "Failure": "Failure",
  "Success": "Success",
  "Authentication": "Authentication",
  "NO": "NO",
  "request header": "Request Headers",
  "Run Query": "Run Query",
  "request body": "Request Body",
  "Close": "Close",
  "Getting Started": "Getting Started",
  "Response": "Response",
  "login to send requests": "Login to change the request type",
  "Share Query": "Share Query",
  "Share this link to let people try your current query in the Graph Explorer.": "Share this link to let people try your current query in the Graph Explorer.",
  "Date": "Date",

  "my profile": "my profile",
  "my files": "my files",
  "my photo": "my photo",
  "my mail": "my mail",
  "my manager": "my manager",

  "Response Headers": "Response Headers",
  "Response Preview": "Response Preview",
  "Sample Queries": "Sample Queries",

  "show more groups": "show more groups",
  "Sample Categories": "Sample Categories",

  "On": "On",
  "Off": "Off",
  "Remove All": "Remove All",

  "Enter new header": "Enter new header",

  "Key": "Key",
  "Value": "Value",

  "Login to try this request": "Login to try this request",

  "modify permissions": "modify permissions",
  "Save changes": "Save changes",
  "To change permissions, you will need to log-in again.": "To change permissions, you will need to log-in again.",

  "all the items in my drive"	:"all the items in my drive",
  "items trending around me"	:"items trending around me",
  "my direct reports"	:"my direct reports",
  "all users in the organization"	:"all users in the organization",
  "all users in the Finance department"	:"all users in the Finance department",
  "my skills"	:"my skills",
  "all my Planner tasks"	:"all my Planner tasks",
  "track user changes"	:"track user changes",
  "all groups in my organization"	:"all groups in my organization",
  "all groups I belong to"	:"all groups I belong to",
  "unified groups I belong to"	:"unified groups I belong to",
  "group members"	:"group members",
  "group's conversations"	:"group's conversations",
  "group's events"	:"group's events",
  "add favorite group"	:"add favorite group",
  "items in a group drive"	:"items in a group drive",
  "track group changes"	:"track group changes",
  "my high important mail"	:"my high important mail",
  "my mail that has 'Hello World'"	:"my mail that has 'Hello World'",
  "send an email"	:"send an email",
  "forward mail"	:"forward mail",
  "track email changes"	:"track email changes",
  "email I'm @ mentioned"	:"email I'm @ mentioned",
  "my events for the next week"	:"my events for the next week",
  "all events in my calendar"	:"all events in my calendar",
  "all my calendars"	:"all my calendars",
  "all my event reminders for next week"	:"all my event reminders for next week",
  "find meeting time"	:"find meeting time",
  "schedule a meeting"	:"schedule a meeting",
  "track changes on my events for the next week"	:"track changes on my events for the next week",
  "my contacts"	:"my contacts",
  "add contact"	:"add contact",
  "my recent files"	:"my recent files",
  "files shared with me"	:"files shared with me",
  "all of my excel files"	:"all of my excel files",
  "create a folder"	:"create a folder",
  "create session"	:"create session",
  "worksheets in a workbook"	:"worksheets in a workbook",
  "add a new worksheet"	:"add a new worksheet",
  "used range in worksheet"	:"used range in worksheet",
  "tables in worksheet"	:"tables in worksheet",
  "charts in worksheet"	:"charts in worksheet",
  "all Planner plans associated with a group"	:"all Planner plans associated with a group",
  "all Planner tasks for a plan"	:"all Planner tasks for a plan",
  "my organization's default SharePoint site"	:"my organization's default SharePoint site",
  "a SharePoint site by URL"	:"a SharePoint site by URL",
  "subsites in a SharePoint site"	:"subsites in a SharePoint site",
  "list in a SharePoint site "	:"list in a SharePoint site ",
  "my notebooks"	:"my notebooks",
  "my sections"	:"my sections",
  "my pages"	:"my pages",
  "create notebook"	:"create notebook",
  "create section"	:"create section",
  "create page"	:"create page",
  "Users":"Users",
  "Users (preview)":"Users (preview)",
  "Groups":"Groups",
  "Groups (preview)":"Groups (preview)",
  "Outlook Mail":"Outlook Mail",
  "Outlook Mail (preview)":"Outlook Mail (preview)",
  "Outlook Calendar":"Outlook Calendar",
  "Outlook Calendar (preview)":"Outlook Calendar (preview)",
  "Personal Contacts":"Personal Contacts",
  "OneDrive":"OneDrive",
  "Excel":"Excel",
  "Planner (beta)":"Planner (beta)",
  "SharePoint Sites (beta)":"SharePoint Sites (beta)",
  "OneNote (beta)":"OneNote (beta)",
  "SharePoint Lists (beta)": "SharePoint Lists (beta)",
  "Insights": "Insights",
  "Insights (preview)": "Insights (preview)"
}

loc_strings['zh-CN'] = {
  "To try the explorer, please ": "若要尝试使用资源管理器，请若要尝试浏览器，请 使用你的 Microsoft 工作或学校帐户 ",
  "sign in": "登录",
  " with your work or school account from Microsoft.": " 使用 Microsoft 提供的工作或学校帐户。",
  "Submit": "提交",
  "Using demo tenant": "当前使用的是示例帐户。",
  "To access your own data:": "若要访问你自己的数据:",
  "sign out": "注销",
  "History": "历史记录",
  "Method": "方法",
  "Query": "查询",
  "Status Code": "状态代码",
  "Duration": "持续时间",
  "Go": "调用",
  "milliseconds": "毫秒",
  "YES": "是",
  "Show More": "显示更多",
  "Graph Explorer": "Graph 浏览器",
  "Failure": "失败",
  "Success": "成功",
  "Authentication": "身份验证",
  "NO": "否",
  "request header": "请求头",
  "Run Query": "运行查询",
  "request body": "请求正文",
  "Close": "关闭",
  "Getting Started": "开始使用",
  "Response": "响应",
  "login to send requests": "登录以更改请求类型",
  "Share Query": "共享查询",
  "Share this link to let people try your current query in the Graph Explorer.": "共享此链接可让其他人在 Graph 浏览器中尝试执行当前查询。",

  "my profile": "我的个人资料",
  "my files": "我的文件",
  "my photo": "我的照片",
  "my mail": "我的邮件",
  "my high importance mail": "我的高重要性邮件",
  "my calendar": "我的日历",
  "my manager": "我的管理器"
}


loc_strings['ja-JP'] = {
  "To try the explorer, please ": "エクスプローラーをお試しいただくには、Microsoft の職場または学校アカウントで ",
  "sign in": "サインイン",
  " with your work or school account from Microsoft.": " します。",
  "Submit": "送信",
  "Using demo tenant": "現在、サンプル アカウントを使用しています。",
  "To access your own data:": "自分のデータにアクセスするには:",
  "sign out": "サインアウト",
  "History": "履歴",
  "Method": "メソッド",
  "Query": "クエリ",
  "Status Code": "状態コード",
  "Duration": "期間",
  "Go": "実行",
  "milliseconds": "ミリ秒",
  "YES": "はい",
  "Show More": "詳細表示",
  "Graph Explorer": "Graph エクスプローラー",
  "Failure": "失敗",
  "Success": "成功",
  "Authentication": "認証",
  "NO": "いいえ",
  "request header": "要求ヘッダー",
  "Run Query": "クエリを実行",
  "request body": "要求本文",
  "Close": "閉じる",
  "Getting Started": "はじめに",
  "Response": "応答",
  "login to send requests": "要求の種類を変更するにはログインしてください",
  "Share Query": "クエリの共有",
  "Share this link to let people try your current query in the Graph Explorer.": "他のユーザーが Graph エクスプローラーで現在のクエリを試せるようにするには、このリンクを共有してください。",

  "my profile": "自分のプロファイル",
  "my files": "自分のファイル",
  "my photo": "自分の写真",
  "my mail": "自分のメール",
  "my high importance mail": "重要度の高い自分のメール",
  "my calendar": "自分の予定表",
  "my manager": "自分の上司"
}


loc_strings['es-ES'] = {
  "To try the explorer, please ": "Para utilizar el probador,  ",
  "sign in": "inicie sesión",
  " with your work or school account from Microsoft.": " con su cuenta profesional o educativa de Microsoft.",
  "Submit": "Enviar",
  "Using demo tenant": "Actualmente está utilizando una cuenta de muestra.",
  "To access your own data:": "Para tener acceso a sus propios datos:",
  "sign out": "Cierre de sesión",
  "History": "Historial",
  "Method": "Método",
  "Query": "Consulta",
  "Status Code": "Código de estado",
  "Duration": "Duración",
  "Go": "Ir",
  "milliseconds": "ms",
  "YES": "SÍ",
  "Show More": "Mostrar más",
  "Graph Explorer": "Probador de Graph",
  "Failure": "Erróneo",
  "Success": "Correcto",
  "Authentication": "Autenticación",
  "NO": "NO",
  "request header": "Encabezados de solicitud",
  "Run Query": "Ejecutar consulta",
  "request body": "Cuerpo de la solicitud",
  "Close": "Cerrar",
  "Getting Started": "Introducción",
  "Response": "Respuesta",
  "login to send requests": "Inicio de sesión para cambiar el tipo de solicitud",
  "Share Query": "Compartir consulta",
  "Share this link to let people try your current query in the Graph Explorer.": "Comparta este vínculo para permitir que la gente intente la consulta actual en el Probador de Graph.",

  "my profile": "mi perfil",
  "my files": "mis archivos",
  "my photo": "mi foto",
  "my mail": "mi correo",
  "my high importance mail": "mi correo electrónico de importancia alta",
  "my calendar": "mi calendario",
  "my manager": "mi administrador"
}


loc_strings['pt-BR'] = {
  "To try the explorer, please ": "Para experimentar o Explorador, ",
  "sign in": "entre",
  " with your work or school account from Microsoft.": " com a sua conta corporativa ou de estudante da Microsoft.",
  "Submit": "Enviar",
  "Using demo tenant": "No momento, você está usando uma conta de exemplo.",
  "To access your own data:": "Para acessar seus dados:",
  "sign out": "Sair",
  "History": "Histórico",
  "Method": "Método",
  "Query": "Consulta",
  "Status Code": "Código de Status",
  "Duration": "Duração",
  "Go": "Ir",
  "milliseconds": "ms",
  "YES": "SIM",
  "Show More": "Mostrar mais",
  "Graph Explorer": "Explorador do Graph",
  "Failure": "Falha",
  "Success": "Êxito",
  "Authentication": "Autenticação",
  "NO": "NÃO",
  "request header": "Cabeçalhos de solicitação",
  "Run Query": "Executar Consulta",
  "request body": "Corpo da Solicitação",
  "Close": "Fechar",
  "Getting Started": "Introdução",
  "Response": "Resposta",
  "login to send requests": "Entre para alterar o tipo de solicitação",
  "Share Query": "Compartilhar Consulta",
  "Share this link to let people try your current query in the Graph Explorer.": "Compartilhe este link para que as pessoas possam experimentar a consulta atual no Explorador do Graph.",

  "my profile": "meu perfil",
  "my files": "meus arquivos",
  "my photo": "minha foto",
  "my mail": "meu email",
  "my high importance mail": "meu email de alta prioridade",
  "my calendar": "meu calendário",
  "my manager": "meu gerente"
}
