// This is a generated file from bundleLocFiles.js 

export const loc_strings = {};

loc_strings['de-DE'] = {
  "Security (beta)": "Sicherheit (Beta)",
  "alerts": "Warnungen",
  "alerts with 'High' severity": "Warnungen mit Schweregrad „Hoch“",
  "alerts related to 'ransomware' category": "Warnungen im Zusammenhang mit der Kategorie „Ransomware“",
  "alerts from 'Azure Security Center'": "Warnungen vom „Azure Security Center“",
  "alerts select by 'Title'": "Warnungen nach „Titel“",
  "To try the explorer, please ": "Um den Tester auszuprobieren, ",
  "sign in": "melden Sie sich",
  " with your work or school account from Microsoft.": " mit Ihrem Geschäfts-, Schul- oder Unikonto von Microsoft an.",
  "Submit": "Senden",
  "Using demo tenant": "Sie verwenden derzeit ein Beispielkonto.",
  "To access your own data:": "So greifen Sie auf Ihre eigenen Daten zu:",
  "sign out": "Abmelden",
  "History": "Verlauf",
  "Method": "Methode",
  "Query": "Abfrage",
  "Status Code": "Statuscode",
  "Duration": "Dauer",
  "Go": "Gehe zu",
  "milliseconds": "ms",
  "YES": "JA",
  "Show More": "Mehr anzeigen",
  "Graph Explorer": "Graph-Tester",
  "Failure": "Misserfolg",
  "Success": "Erfolg",
  "Authentication": "Authentifizierung",
  "NO": "NEIN",
  "request header": "Anforderungsheader",
  "Request body editor": "Anforderungstext-Editor",
  "Run Query": "Abfrage ausführen",
  "request body": "Anforderungstext",
  "Close": "Schließen",
  "Getting Started": "Erste Schritte",
  "Response": "Antwort",
  "login to send requests": "Melden Sie an, um den Anforderungstyp zu ändern",
  "HTTP verb selector": "HTTP-Verbselektor",
  "Share Query": "Abfrage freigeben",
  "Share this link to let people try your current query in the Graph Explorer.": "Teilen Sie diesen Link, damit Benutzer Ihre aktuelle Abfrage im Graph-Tester testen können.",
  "Date": "Datum",
  "my profile": "Mein Profil",
  "my files": "meine Dateien",
  "my photo": "Mein Foto",
  "my mail": "Meine E-Mail",
  "my manager": "Mein Vorgesetzter",
  "User photo": "Foto des angemeldeten Benutzers",
  "Response Headers": "Antwortheader",
  "Response headers viewer": "Die von Microsoft Graph zurückgegebenen Antwortheader",
  "Response body": "Der von Microsoft Graph zurückgegebene Antworttext",
  "Response Preview": "Antwortvorschau",
  "Sample Queries": "Beispielabfragen",
  "show more samples": "Mehr Beispiele anzeigen",
  "Sample Categories": "Beispielkategorien",
  "On": "Ein",
  "Off": "Off",
  "Remove All": "Alle entfernen",
  "Enter new header": "Neuen Header eingeben",
  "Key": "Schlüssel",
  "Value": "Wert",
  "Login to try this request": "Melden Sie sich an, um diese Anforderung zu testen",
  "modify permissions": "Berechtigungen ändern",
  "Save changes": "Änderungen speichern",
  "To change permissions, you will need to log-in again.": "Um Berechtigungen zu ändern, müssen Sie sich erneut anmelden.",
  "all the items in my drive": "Alle Elemente in meinem Laufwerk",
  "items trending around me": "Populäre Elemente",
  "my direct reports": "Meine Mitarbeiter",
  "all users in the organization": "Alle Benutzer in der Organisation",
  "all users in the Finance department": "Alle Benutzer in der Finanzabteilung",
  "my skills": "Meine Skills",
  "all my Planner tasks": "Alle meine Planner-Aufgaben",
  "track user changes": "Benutzeränderungen nachverfolgen",
  "all groups in my organization": "Alle Benutzer in meiner Organisation",
  "all groups I belong to": "Alle Gruppen, bei denen ich Mitglied bin",
  "unified groups I belong to": "Einheitliche Gruppen, bei denen ich Mitglied bin",
  "group members": "Gruppenmitglieder",
  "group's conversations": "Gruppenunterhaltungen",
  "group's events": "Gruppenereignisse",
  "add favorite group": "Favoritengruppe hinzufügen",
  "items in a group drive": "Elemente in einem Gruppenlaufwerk",
  "track group changes": "Gruppenänderungen nachverfolgen",
  "my high important mail": "Meine E-Mails mit Wichtigkeit „Hoch“",
  "my mail that has 'Hello World'": "Meine E-Mail, die „Hello World“ enthält",
  "send an email": "E-Mail senden",
  "forward mail": "E-Mail weiterleiten",
  "track email changes": "E-Mail-Änderungen nachverfolgen",
  "email I'm @ mentioned": "E-Mail, in der ich @-erwähnt werde",
  "my events for the next week": "Meine Ereignisse für die nächste Woche",
  "all events in my calendar": "Alle Ereignisse im meinem Kalender",
  "all my calendars": "Alle meinen Kalender",
  "all my event reminders for next week": "Alle meine Ereigniserinnerungen für nächste Woche",
  "find meeting time": "Besprechungszeit suchen",
  "schedule a meeting": "Besprechung planen",
  "track changes on my events for the next week": "Änderungen meiner Ereignisse für die nächste Woche nachverfolgen",
  "my contacts": "Meine Kontakte",
  "add contact": "Kontakt hinzufügen",
  "my recent files": "Meine zuletzt verwendete Dateien",
  "files shared with me": "Mit mir geteilte Dateien",
  "all of my excel files": "Alle meine Excel-Dateien",
  "create a folder": "Ordner erstellen",
  "create session": "Sitzung erstellen",
  "worksheets in a workbook": "Arbeitsblätter in einer Arbeitsmappe",
  "add a new worksheet": "Neues Arbeitsblatt hinzufügen",
  "used range in worksheet": "Im Arbeitsblatt verwendeter Bereich",
  "tables in worksheet": "Tabellen im Arbeitsblatt",
  "charts in worksheet": "Diagramme im Arbeitsblatt",
  "all Planner plans associated with a group": "Alle einer Gruppe zugeordneten Planner-Pläne",
  "all Planner tasks for a plan": "Alle Planner-Aufgaben für einen Plan",
  "my organization's default SharePoint site": "SharePoint-Standardwebsite meiner Organisation",
  "a SharePoint site by URL": "SharePoint-Website nach URL",
  "subsites in a SharePoint site": "Unterwebsites einer SharePoint-Website",
  "list in a SharePoint site ": "Liste auf einer SharePoint-Website ",
  "my notebooks": "Meine Notizbücher",
  "my sections": "Meine Abschnitte",
  "my pages": "Meine Seiten",
  "my inbox rules": "Meine Posteingangsregeln",
  "my outlook categories": "Meine Outlook-Kategorien",
  "get email headers": "E-Mail-Header abrufen",
  "list conference rooms": "Konferenzräume auflisten",
  "create notebook": "Notizbuch erstellen",
  "create section": "Abschnitt erstellen",
  "create page": "Seite erstellen",
  "Users": "Benutzer",
  "Users (beta)": "Benutzer (Beta)",
  "Groups": "Gruppen",
  "Groups (beta)": "Gruppen (Beta)",
  "Outlook Mail": "Outlook Mail",
  "Outlook Mail (beta)": "Outlook Mail (Beta)",
  "Outlook Calendar": "Outlook-Kalender",
  "Outlook Calendar (beta)": "Outlook-Kalender (Beta)",
  "Personal Contacts": "Private Kontakte",
  "OneDrive": "OneDrive",
  "Excel": "Excel",
  "Planner (beta)": "Planner (Beta)",
  "SharePoint Sites (beta)": "SharePoint-Websites (Beta)",
  "SharePoint Lists": "SharePoint-Listen",
  "OneNote (beta)": "OneNote (Beta)",
  "SharePoint Lists (beta)": "SharePoint-Listen (Beta)",
  "Insights": "Insights",
  "Insights (beta)": "Insights (Beta)",
  "Preview": "Vorschau",
  "People": "Personen",
  "Extensions (beta)": "Extensions (Beta)",
  "Batching": "Batchverarbeitung",
  "Extensions": "Extensions",
  "OneNote": "OneNote",
  "Planner": "Planner",
  "SharePoint Sites": "SharePoint-Websites",
  "Microsoft Teams (beta)": "Microsoft Teams (Beta)",
  "all buckets in Planner plan": "Alle Buckets im Planner-Plan",
  "all Planner tasks for user": "Alle Planner-Aufgaben für Benutzer",
  "calculate loan payment": "Darlehenszahlung berechnen",
  "channel info": "Kanalinformationen",
  "channels of a team which I am member of": "Kanäle eines Teams, in dem ich Mitglied bin",
  "Combine a POST and a GET": "POST und GET kombinieren",
  "create a bucket in Planner plan": "Bucket im Planner-Plan erstellen",
  "create a group with extension data": "Gruppe mit Erweiterungsdaten erstellen",
  "create a Planner task": "Planner-Aufgabe erstellen",
  "create an open extension": "Offene Erweiterung erstellen",
  "create channel": "Kanal erstellen",
  "create chat thread": "Chatthread erstellen",
  "create user": "Benutzer erstellen",
  "details for Planner task": "Details zur Planner-Aufgabe",
  "Enumerate list columns": "Listenspalten auflisten",
  "Enumerate list content types": "Listeninhaltstypen auflisten",
  "Enumerate list items with specific column values": "Listenelemente mit bestimmten Spaltenwerten auflisten",
  "Enumerate site columns of the root site": "Websites der Stammwebsite auflisten",
  "Enumerate site content types of the root site": "Websiteinhaltstypen der Stammwebsite auflisten",
  "Enumerate subsites of the root site": "Unterwebsites der Stammwebsite aufzählen",
  "Enumerate the document libraries under the root site": "Dokumentbibliotheken unter der Stammwebsite aufzählen",
  "Enumerate the lists in the root site": "Listen in der Stammwebsite aufzählen",
  "Enumerate the list items in a list": "Die Listenelemente in einer Liste aufzählen",
  "filter groups by extension property value": "Gruppen nach Wert von Erweiterungseigenschaft filtern",
  "get an open extension": "Offene Erweiterung abrufen",
  "get available schema extensions": "Verfügbare Schemaerweiterungen abrufen",
  "items in a team drive": "Elemente in einer Teamlaufwerk",
  "members of a team": "Mitglieder eines Teams",
  "my joined teams": "Meine verknüpften Teams",
  "my mails from an address": "Meine E-Mails von einer Adresse",
  "people I work with": "Personen, mit denen ich arbeite",
  "people relevant to a topic": "Personen, die für ein Thema relevant sind",
  "people whose name starts with J": "Personen, deren Name mit J beginnt",
  "Perform parallel GETs": "Parallele GET-Vorgänge durchführen",
  "Planner plan": "Planner-Plan",
  "Planner task by id": "Planner-Aufgabe nach ID",
  "Search for a SharePoint site by keyword": "SharePoint-Website nach Schlüsselwort suchen",
  "SharePoint site based on relative path of the site": "SharePoint-Website basierend auf relativem Pfad der Website",
  "update a bucket in Planner plan": "Bucket im Planner-Plan aktualisieren",
  "update a group with extension data": "Gruppe mit Erweiterungsdaten aktualisieren",
  "update a Planner plan": "Planner-Plan aktualisieren",
  "update a Planner task": "Planner-Aufgabe aktualisieren",
  "update an open extension": "Offene Erweiterung aktualisieren",
  "user by email": "Benutzer nach E-Mail",
  "explorer-error": "Beim Senden dieser Anforderung an die Graph-API ist ein Fehler aufgetreten.  Um Unterstützung zu erhalten, verbinden Sie sich mit uns auf StackOverflow, und verwenden Sie dazu das Tag [microsoftgraph].",
  "search my OneDrive": "mein OneDrive durchsuchen",
  "User Activities": "Benutzeraktivitäten",
  "get recent user activities": "Aktuelle Benutzeraktivitäten abrufen",
  "create a user activity and history item": "Benutzeraktivitäts- und Verlaufselement erstellen"
}

loc_strings['es-ES'] = {
  "Security (beta)": "Seguridad (beta)",
  "alerts": "alertas",
  "alerts with 'High' severity": "alertas con estado de gravedad alto",
  "alerts related to 'ransomware' category": "alertas relacionadas con la categoría “ransomware”",
  "alerts from 'Azure Security Center'": "alertas de “Azure Security Center”",
  "alerts select by 'Title'": "seleccionar alertas por “Título”",
  "To try the explorer, please ": "Para utilizar el probador, ",
  "sign in": "inicie sesión",
  " with your work or school account from Microsoft.": " con su cuenta profesional o educativa de Microsoft.",
  "Submit": "Enviar",
  "Using demo tenant": "Actualmente está utilizando una cuenta de muestra.",
  "To access your own data:": "Para tener acceso a sus propios datos:",
  "sign out": "cerrar sesión",
  "History": "Historial",
  "Method": "Método",
  "Query": "Consulta",
  "Status Code": "Código de estado",
  "Duration": "Duración",
  "Go": "Ir",
  "milliseconds": "ms",
  "YES": "SÍ",
  "Show More": "mostrar más",
  "Graph Explorer": "Probador de Graph",
  "Failure": "Erróneo",
  "Success": "Correcto",
  "Authentication": "Autenticación",
  "NO": "NO",
  "request header": "Encabezados de solicitud",
  "Request body editor": "Editor del cuerpo de la solicitud",
  "Run Query": "Ejecutar consulta",
  "request body": "Cuerpo de la solicitud",
  "Close": "Cerrar",
  "Getting Started": "Introducción",
  "Response": "Respuesta",
  "login to send requests": "Inicio de sesión para cambiar el tipo de solicitud",
  "HTTP verb selector": "Selector de verbo HTTP",
  "Share Query": "Compartir consulta",
  "Share this link to let people try your current query in the Graph Explorer.": "Comparta este vínculo para permitir que la gente intente la consulta actual en el Probador de Graph.",
  "Date": "Fecha",
  "my profile": "mi perfil",
  "my files": "mis archivos",
  "my photo": "mi foto",
  "my mail": "mi correo",
  "my manager": "mi administrador",
  "User photo": "foto del usuario que ha iniciado sesión",
  "Response Headers": "Encabezados de respuesta",
  "Response headers viewer": "Encabezados de respuesta devueltos por Microsoft Graph",
  "Response body": "Cuerpo de la respuesta devuelto por Microsoft Graph",
  "Response Preview": "Vista previa de la respuesta",
  "Sample Queries": "Consultas de ejemplo",
  "show more samples": "mostrar más ejemplos",
  "Sample Categories": "Categorías de ejemplo",
  "On": "Activado",
  "Off": "Desactivado",
  "Remove All": "Quitar todo",
  "Enter new header": "Introducir encabezado nuevo",
  "Key": "Clave",
  "Value": "Valor",
  "Login to try this request": "Inicie sesión para intentar esta solicitud",
  "modify permissions": "modificar permisos",
  "Save changes": "Guardar cambios",
  "To change permissions, you will need to log-in again.": "Para cambiar los permisos, debe volver a iniciar sesión.",
  "all the items in my drive": "todos los elementos de la unidad",
  "items trending around me": "elementos populares de mi entorno",
  "my direct reports": "mis informes directos",
  "all users in the organization": "todos los usuarios de la organización",
  "all users in the Finance department": "todos los usuarios del departamento de finanzas",
  "my skills": "mis habilidades",
  "all my Planner tasks": "todas mis tareas de Planner",
  "track user changes": "hacer un seguimiento de los cambios de los usuarios",
  "all groups in my organization": "todos los grupos de la organización",
  "all groups I belong to": "todos los grupos a los que pertenezco",
  "unified groups I belong to": "grupos unificados a los que pertenezco",
  "group members": "miembros del grupo",
  "group's conversations": "conversaciones del grupo",
  "group's events": "eventos del grupo",
  "add favorite group": "agregar grupo favorito",
  "items in a group drive": "elementos de una unidad de grupo",
  "track group changes": "hacer un seguimientos de los cambios en los grupos",
  "my high important mail": "mi correo de importancia alta",
  "my mail that has 'Hello World'": "mi correo que contiene \"Hola a todos\"",
  "send an email": "enviar un correo electrónico",
  "forward mail": "reenviar correo electrónico",
  "track email changes": "hacer un seguimiento de los cambios en el correo electrónico",
  "email I'm @ mentioned": "correo electrónico en el que se me menciona",
  "my events for the next week": "mis eventos para la próxima semana",
  "all events in my calendar": "todos los eventos en mi calendario",
  "all my calendars": "todos mis calendarios",
  "all my event reminders for next week": "todos mis recordatorios de eventos para la próxima semana",
  "find meeting time": "buscar horas de reunión",
  "schedule a meeting": "programar una reunión",
  "track changes on my events for the next week": "hacer un seguimiento de mis eventos para la próxima semana",
  "my contacts": "mis contactos",
  "add contact": "agregar contacto",
  "my recent files": "mis archivos recientes",
  "files shared with me": "archivos compartidos conmigo",
  "all of my excel files": "todos mis archivos de Excel",
  "create a folder": "crear una carpeta",
  "create session": "crear una sesión",
  "worksheets in a workbook": "hojas de cálculo de un libro",
  "add a new worksheet": "agregar una hoja de cálculo nueva",
  "used range in worksheet": "rango utilizado en una hoja de cálculo",
  "tables in worksheet": "tablas en una hoja de cálculo",
  "charts in worksheet": "gráficos en una hoja de cálculo",
  "all Planner plans associated with a group": "todos los planes de Planner asociados a un grupo",
  "all Planner tasks for a plan": "todas las tareas de Planner para un plan",
  "my organization's default SharePoint site": "sitio de SharePoint predeterminado de mi organización",
  "a SharePoint site by URL": "un sitio de SharePoint por la dirección URL",
  "subsites in a SharePoint site": "subsitios de un sitio de SharePoint",
  "list in a SharePoint site ": "lista de un sitio de SharePoint ",
  "my notebooks": "mis blocs de notas",
  "my sections": "mis secciones",
  "my pages": "mis páginas",
  "my inbox rules": "mis reglas de la Bandeja de entrada",
  "my outlook categories": "mis categorías de Outlook",
  "get email headers": "obtener encabezados de correo electrónico",
  "list conference rooms": "lista de las salas de conferencias",
  "create notebook": "crear bloc de notas",
  "create section": "crear sección",
  "create page": "crear página",
  "Users": "Usuarios",
  "Users (beta)": "Usuarios (beta)",
  "Groups": "Grupos",
  "Groups (beta)": "Grupos (beta)",
  "Outlook Mail": "Correo de Outlook",
  "Outlook Mail (beta)": "Correo de Outlook (beta)",
  "Outlook Calendar": "Calendario de Outlook",
  "Outlook Calendar (beta)": "Calendario de Outlook (beta)",
  "Personal Contacts": "Contactos personales",
  "OneDrive": "OneDrive",
  "Excel": "Excel",
  "Planner (beta)": "Planner (versión beta)",
  "SharePoint Sites (beta)": "Sitios de SharePoint (versión beta)",
  "SharePoint Lists": "Listas de SharePoint",
  "OneNote (beta)": "OneNote (versión beta)",
  "SharePoint Lists (beta)": "Listas de SharePoint (versión beta)",
  "Insights": "Información",
  "Insights (beta)": "Información (beta)",
  "Preview": "Vista previa",
  "People": "Contactos",
  "Extensions (beta)": "Extensiones (beta)",
  "Batching": "Procesamiento por lotes",
  "Extensions": "Extensiones",
  "OneNote": "OneNote",
  "Planner": "Planner",
  "SharePoint Sites": "Sitios de SharePoint",
  "Microsoft Teams (beta)": "Microsoft Teams (beta)",
  "all buckets in Planner plan": "todos los cubos de un plan de Planner",
  "all Planner tasks for user": "todas las tareas de Planner de un usuario",
  "calculate loan payment": "cálculo del pago del préstamo",
  "channel info": "información del canal",
  "channels of a team which I am member of": "canales de un equipo del que soy miembro",
  "Combine a POST and a GET": "Combinar una operación POST con una GET",
  "create a bucket in Planner plan": "crear un cubo en un plan de Planner",
  "create a group with extension data": "crear un grupo con datos de extensión",
  "create a Planner task": "crear una tarea de Planner",
  "create an open extension": "crear una extensión abierta",
  "create channel": "crear un canal",
  "create chat thread": "crear un subproceso de chat",
  "create user": "crear un usuario",
  "details for Planner task": "detalles de una tarea de Planner",
  "Enumerate list columns": "Enumerar las columnas de lista",
  "Enumerate list content types": "Enumerar los tipos de contenido de lista",
  "Enumerate list items with specific column values": "Enumerar los elementos de lista con valores de columna específicos",
  "Enumerate site columns of the root site": "Enumerar las columnas de sitio del sitio raíz",
  "Enumerate site content types of the root site": "Enumerar los tipos de contenido de sitio del sitio raíz",
  "Enumerate subsites of the root site": "Enumerar los subsitios del sitio raíz",
  "Enumerate the document libraries under the root site": "Enumerar las bibliotecas de documentos en el sitio raíz",
  "Enumerate the lists in the root site": "Enumerar las listas del sitio raíz",
  "Enumerate the list items in a list": "Enumerar los elementos de lista de una lista",
  "filter groups by extension property value": "filtrar grupos por valor de propiedad de extensión",
  "get an open extension": "obtener una extensión abierta",
  "get available schema extensions": "obtener extensiones de esquema disponibles",
  "items in a team drive": "elementos de una unidad de equipo",
  "members of a team": "miembros de un equipo",
  "my joined teams": "equipos a los que me he unido",
  "my mails from an address": "mis correos desde una dirección",
  "people I work with": "personas con las que trabajo",
  "people relevant to a topic": "personas pertinentes para un tema",
  "people whose name starts with J": "personas cuyo nombre empiece por J",
  "Perform parallel GETs": "Realizar operaciones GET paralelas",
  "Planner plan": "plan de Planner",
  "Planner task by id": "tarea de Planner por id.",
  "Search for a SharePoint site by keyword": "Buscar un sitio de SharePoint por palabra clave",
  "SharePoint site based on relative path of the site": "Sitio de SharePoint basado en la ruta de acceso relativa del sitio",
  "update a bucket in Planner plan": "actualizar un cubo en un plan de Planner",
  "update a group with extension data": "actualizar un grupo con datos de extensión",
  "update a Planner plan": "actualizar un plan de Planner",
  "update a Planner task": "actualizar una tarea de Planner",
  "update an open extension": "actualizar una extensión abierta",
  "user by email": "usuario por correo electrónico",
  "explorer-error": "Se ha producido un problema al enviar esta solicitud a la API de Graph.  Para obtener ayuda, póngase en contacto con nosotros en StackOverflow con la etiqueta [microsoftgraph].",
  "search my OneDrive": "buscar en mi OneDrive",
  "User Activities": "Actividades de usuario",
  "get recent user activities": "obtener actividades de usuario recientes",
  "create a user activity and history item": "crear una actividad de usuario y un elemento de historial"
}

loc_strings['pt-BR'] = {
  "Security (beta)": "Segurança (beta)",
  "alerts": "alertas",
  "alerts with 'High' severity": "alertas com severidade \"Alta\"",
  "alerts related to 'ransomware' category": "alertas relacionados à categoria \"ransomware\"",
  "alerts from 'Azure Security Center'": "alertas da \"Central de Segurança do Azure\"",
  "alerts select by 'Title'": "seleção de alertas por \"Título\"",
  "To try the explorer, please ": "Para experimentar o Explorador, ",
  "sign in": "entre",
  " with your work or school account from Microsoft.": " com a sua conta corporativa ou de estudante da Microsoft.",
  "Submit": "Enviar",
  "Using demo tenant": "No momento, você está usando uma conta de amostra.",
  "To access your own data:": "Para acessar seus dados:",
  "sign out": "sair",
  "History": "Histórico",
  "Method": "Método",
  "Query": "Consulta",
  "Status Code": "Código de Status",
  "Duration": "Duração",
  "Go": "Ir",
  "milliseconds": "ms",
  "YES": "SIM",
  "Show More": "mostrar mais",
  "Graph Explorer": "Explorador do Graph",
  "Failure": "Falha",
  "Success": "Êxito",
  "Authentication": "Autenticação",
  "NO": "NÃO",
  "request header": "Cabeçalhos da Solicitação",
  "Request body editor": "Editor do corpo da solicitação",
  "Run Query": "Executar Consulta",
  "request body": "Corpo da Solicitação",
  "Close": "Fechar",
  "Getting Started": "Introdução",
  "Response": "Resposta",
  "login to send requests": "Entre para alterar o tipo de solicitação",
  "HTTP verb selector": "Seletor de verbo HTTP",
  "Share Query": "Compartilhar consulta",
  "Share this link to let people try your current query in the Graph Explorer.": "Compartilhe este link para que as pessoas possam experimentar a consulta atual no Explorador do Graph.",
  "Date": "Data",
  "my profile": "meu perfil",
  "my files": "meus arquivos",
  "my photo": "minha foto",
  "my mail": "meu email",
  "my manager": "meu gerente",
  "User photo": "foto do usuário conectado",
  "Response Headers": "Cabeçalhos de respostas",
  "Response headers viewer": "Os cabeçalhos de respostas retornados pelo Microsoft Graph",
  "Response body": "O corpo de respostas retornados pelo Microsoft Graph",
  "Response Preview": "Visualização da resposta",
  "Sample Queries": "Consultas de amostra",
  "show more samples": "mostrar mais amostras",
  "Sample Categories": "Categorias de amostra",
  "On": "Habilitado",
  "Off": "Desabilitado",
  "Remove All": "Remover Tudo",
  "Enter new header": "Inserir novo cabeçalho",
  "Key": "Chave",
  "Value": "Valor",
  "Login to try this request": "Entre para testar esta solicitação",
  "modify permissions": "modificar permissões",
  "Save changes": "Salvar alterações",
  "To change permissions, you will need to log-in again.": "Para alterar permissões, entre novamente.",
  "all the items in my drive": "todos os itens da minha unidade",
  "items trending around me": "itens mais populares à minha volta",
  "my direct reports": "meus subordinados diretos",
  "all users in the organization": "todos os usuários da organização",
  "all users in the Finance department": "todos os usuários do departamento financeiro",
  "my skills": "minhas habilidades",
  "all my Planner tasks": "todas as minhas tarefas do Planner",
  "track user changes": "controlar alterações do usuário",
  "all groups in my organization": "todos os grupos em minha organização",
  "all groups I belong to": "todos os grupos aos quais pertenço",
  "unified groups I belong to": "grupos unificados aos quais pertenço",
  "group members": "membros do grupo",
  "group's conversations": "conversas do grupo",
  "group's events": "eventos do grupo",
  "add favorite group": "adicionar grupo favorito",
  "items in a group drive": "itens de uma unidade de grupo",
  "track group changes": "controlar alterações do grupo",
  "my high important mail": "meu email de alta prioridade",
  "my mail that has 'Hello World'": "meu email que tenha \"Hello World\"",
  "send an email": "enviar um email",
  "forward mail": "encaminhar email",
  "track email changes": "controlar alterações de email",
  "email I'm @ mentioned": "email no qual sou @ mencionado",
  "my events for the next week": "meus eventos para a próxima semana",
  "all events in my calendar": "todos os eventos do meu calendário",
  "all my calendars": "todos os meus calendários",
  "all my event reminders for next week": "todos os meus lembretes de eventos para a próxima semana",
  "find meeting time": "encontrar horário da reunião",
  "schedule a meeting": "agendar uma reunião",
  "track changes on my events for the next week": "controlar alterações em meus eventos para a próxima semana",
  "my contacts": "meus contatos",
  "add contact": "adicionar contato",
  "my recent files": "meus arquivos recentes",
  "files shared with me": "arquivos compartilhados comigo",
  "all of my excel files": "todos os meus arquivos do Excel",
  "create a folder": "criar uma pasta",
  "create session": "criar sessão",
  "worksheets in a workbook": "planilhas em uma pasta de trabalho",
  "add a new worksheet": "adicionar uma nova planilha",
  "used range in worksheet": "intervalo usado em uma planilha",
  "tables in worksheet": "tabelas da planilha",
  "charts in worksheet": "gráficos da planilha",
  "all Planner plans associated with a group": "todos os planos do Planner associados a um grupo",
  "all Planner tasks for a plan": "todas as tarefas do Planner para um plano",
  "my organization's default SharePoint site": "site padrão do SharePoint da minha organização",
  "a SharePoint site by URL": "um site do SharePoint pela URL",
  "subsites in a SharePoint site": "subsites de um site do SharePoint",
  "list in a SharePoint site ": "lista em um site do SharePoint ",
  "my notebooks": "meus blocos de anotações",
  "my sections": "minhas seções",
  "my pages": "minhas páginas",
  "my inbox rules": "minhas regras da caixa de entrada",
  "my outlook categories": "minhas categorias do Outlook",
  "get email headers": "obter cabeçalhos de email",
  "list conference rooms": "enumerar salas de conferência",
  "create notebook": "criar bloco de anotações",
  "create section": "criar seção",
  "create page": "criar página",
  "Users": "Usuários",
  "Users (beta)": "Usuários (beta)",
  "Groups": "Grupos",
  "Groups (beta)": "Grupos (beta)",
  "Outlook Mail": "Email do Outlook",
  "Outlook Mail (beta)": "Email do Outlook (beta)",
  "Outlook Calendar": "Calendário do Outlook",
  "Outlook Calendar (beta)": "Calendário do Outlook (beta)",
  "Personal Contacts": "Contatos Pessoais",
  "OneDrive": "OneDrive",
  "Excel": "Excel",
  "Planner (beta)": "Planner (beta)",
  "SharePoint Sites (beta)": "Sites do SharePoint (beta)",
  "SharePoint Lists": "Listas do SharePoint",
  "OneNote (beta)": "OneNote (beta)",
  "SharePoint Lists (beta)": "Listas do SharePoint (beta)",
  "Insights": "Insights",
  "Insights (beta)": "Insights (beta)",
  "Preview": "Visualização",
  "People": "Pessoas",
  "Extensions (beta)": "Extensões (beta)",
  "Batching": "Envio em lote",
  "Extensions": "Extensões",
  "OneNote": "OneNote",
  "Planner": "Planner",
  "SharePoint Sites": "Sites do SharePoint",
  "Microsoft Teams (beta)": "Microsoft Teams (beta)",
  "all buckets in Planner plan": "todos os buckets no plano do Planner",
  "all Planner tasks for user": "todas as tarefas do Planner de usuário",
  "calculate loan payment": "calcular pagamento de empréstimo",
  "channel info": "informações de canal",
  "channels of a team which I am member of": "canais de uma equipe da qual sou membro",
  "Combine a POST and a GET": "Combinar um POST e um GET",
  "create a bucket in Planner plan": "criar um bucket no plano do Planner",
  "create a group with extension data": "criar um grupo com dados de extensão",
  "create a Planner task": "criar uma tarefa do Planner",
  "create an open extension": "criar uma extensão aberta",
  "create channel": "criar canal",
  "create chat thread": "criar thread de chat",
  "create user": "criar usuário",
  "details for Planner task": "detalhes da tarefa do Planner",
  "Enumerate list columns": "Enumerar colunas de lista",
  "Enumerate list content types": "Enumerar tipos de conteúdo de lista",
  "Enumerate list items with specific column values": "Enumerar itens de lista com valores de uma coluna específica",
  "Enumerate site columns of the root site": "Enumerar colunas de site do site raiz",
  "Enumerate site content types of the root site": "Enumerar tipos de conteúdo de site do site raiz",
  "Enumerate subsites of the root site": "Enumerar subsites do site raiz",
  "Enumerate the document libraries under the root site": "Enumerar as bibliotecas de documentos no site raiz",
  "Enumerate the lists in the root site": "Enumerar as listas do site raiz",
  "Enumerate the list items in a list": "Enumerar os itens de lista em uma lista",
  "filter groups by extension property value": "filtrar grupos pelo valor da propriedade de extensão",
  "get an open extension": "obter uma extensão aberta",
  "get available schema extensions": "obter extensões de esquema disponíveis",
  "items in a team drive": "itens em uma unidade de equipe",
  "members of a team": "membros de uma equipe",
  "my joined teams": "minhas equipes unidas",
  "my mails from an address": "meus emails de um endereço",
  "people I work with": "pessoas que trabalham comigo",
  "people relevant to a topic": "pessoas relevantes para um tópico",
  "people whose name starts with J": "pessoas cujos nomes começam com J",
  "Perform parallel GETs": "Executar GETs paralelos",
  "Planner plan": "Plano do Planner",
  "Planner task by id": "tarefa do Planner por id",
  "Search for a SharePoint site by keyword": "Pesquisar um site do SharePoint por palavra-chave",
  "SharePoint site based on relative path of the site": "Site do SharePoint baseado no caminho relativo do site",
  "update a bucket in Planner plan": "atualizar um bucket no plano do Planner",
  "update a group with extension data": "atualizar um grupo com dados de extensão",
  "update a Planner plan": "atualizar um plano do Planner",
  "update a Planner task": "atualizar uma tarefa do Planner",
  "update an open extension": "atualizar uma extensão aberta",
  "user by email": "usuário por email",
  "explorer-error": "Tivemos um problema ao enviar esta solicitação à API do Graph.  Para receber ajuda, envie uma mensagem no StackOverflow com a marca [microsoftgraph].",
  "search my OneDrive": "pesquisar meu OneDrive",
  "User Activities": "Atividades do usuário",
  "get recent user activities": "obter as atividades recentes do usuário",
  "create a user activity and history item": "criar um item de histórico e atividade do usuário"
}

loc_strings['fr-FR'] = {
  "Security (beta)": "Sécurité (bêta)",
  "alerts": "alertes",
  "alerts with 'High' severity": "alertes de gravité élevée",
  "alerts related to 'ransomware' category": "alertes relatives à la catégorie ransomware",
  "alerts from 'Azure Security Center'": "alertes Azure Security Center",
  "alerts select by 'Title'": "sélection des alertes par titre",
  "To try the explorer, please ": "Pour essayer l’afficheur, veuillez ",
  "sign in": "vous connecter",
  " with your work or school account from Microsoft.": " avec votre compte scolaire ou professionnel de Microsoft.",
  "Submit": "Submit",
  "Using demo tenant": "Vous utilisez actuellement un compte factice.",
  "To access your own data:": "Pour accéder à vos données :",
  "sign out": "se déconnecter",
  "History": "Historique de requêtes",
  "Method": "Méthode",
  "Query": "Requête",
  "Status Code": "Code",
  "Duration": "Durée",
  "Go": "OK",
  "milliseconds": "ms",
  "YES": "OUI",
  "Show More": "voir tout l'historique",
  "Graph Explorer": "Afficheur Graph",
  "Failure": "Échec",
  "Success": "Opération réussie",
  "Authentication": "Authentification",
  "NO": "NON",
  "request header": "En-têtes de requête",
  "Request body editor": "Éditeur de corps de requête",
  "Run Query": "Exécuter",
  "request body": "Corps de la requête",
  "Close": "Fermer",
  "Getting Started": "Requêtes de base",
  "Response": "Réponse",
  "login to send requests": "Se connecter pour modifier le type de requête",
  "HTTP verb selector": "Sélecteur de verbe HTTP",
  "Share Query": "Partager la requête",
  "Share this link to let people try your current query in the Graph Explorer.": "Partagez ce lien pour permettre aux utilisateurs d’essayer votre requête actuelle dans l’Afficheur Graph.",
  "Date": "Date",
  "my profile": "mon profil",
  "my files": "mes fichiers",
  "my photo": "ma photo",
  "my mail": "mon courrier électronique",
  "my manager": "mon responsable",
  "User photo": "photo de l’utilisateur connecté",
  "Response Headers": "En-têtes de réponse",
  "Response headers viewer": "Les en-têtes de réponse sont renvoyés par Microsoft Graph.",
  "Response body": "Le corps de la réponse est renvoyé par Microsoft Graph.",
  "Response Preview": "Aperçu de la réponse",
  "Sample Queries": "Exemples de requêtes",
  "show more samples": "voir d'autres exemples",
  "Sample Categories": "Exemples de catégories",
  "On": "Activé",
  "Off": "Désactivé",
  "Remove All": "Supprimer tout",
  "Enter new header": "Entrez une nouvelle clé",
  "Key": "Clé",
  "Value": "Valeur",
  "Login to try this request": "Connectez-vous pour tester cette demande",
  "modify permissions": "modifier les autorisations",
  "Save changes": "Enregistrer les modifications",
  "To change permissions, you will need to log-in again.": "Pour modifier les autorisations, vous devez vous reconnecter.",
  "all the items in my drive": "tous les éléments de mon disque",
  "items trending around me": "éléments qui me sont suggérés",
  "my direct reports": "mes collaborateurs directs",
  "all users in the organization": "tous les utilisateurs de l’organisation",
  "all users in the Finance department": "tous les utilisateurs du service financier",
  "my skills": "mes compétences",
  "all my Planner tasks": "toutes mes tâches du planificateur",
  "track user changes": "suivre les modifications d’utilisateur",
  "all groups in my organization": "tous les groupes de mon organisation",
  "all groups I belong to": "tous les groupes auxquels j’appartiens",
  "unified groups I belong to": "groupes unifiés auxquels j’appartiens",
  "group members": "membres du groupe",
  "group's conversations": "conversations du groupe",
  "group's events": "événements du groupe",
  "add favorite group": "ajouter un groupe favori",
  "items in a group drive": "éléments d’un lecteur de groupe",
  "track group changes": "suivre les modifications de groupe",
  "my high important mail": "mon courrier importance haute",
  "my mail that has 'Hello World'": "mon courrier contenant « Hello World »",
  "send an email": "envoyer un courrier",
  "forward mail": "transférer un courrier",
  "track email changes": "suivre les modifications de courrier",
  "email I'm @ mentioned": "courrier où je suis mentionné",
  "my events for the next week": "mes événements pour la semaine prochaine",
  "all events in my calendar": "tous les événements de mon calendrier",
  "all my calendars": "tous mes calendriers",
  "all my event reminders for next week": "tous mes rappels d’événement pour la semaine prochaine",
  "find meeting time": "rechercher l’heure de la réunion",
  "schedule a meeting": "planifier une réunion",
  "track changes on my events for the next week": "suivre les modifications de mes événements de la semaine prochaine",
  "my contacts": "mes contacts",
  "add contact": "ajouter un contact",
  "my recent files": "mes fichiers récents",
  "files shared with me": "fichiers partagés avec moi",
  "all of my excel files": "tous mes fichiers excel",
  "create a folder": "créer un dossier",
  "create session": "créer une session",
  "worksheets in a workbook": "feuilles de calcul d’un classeur",
  "add a new worksheet": "ajouter une nouvelle feuille de calcul",
  "used range in worksheet": "plage utilisée dans la feuille de calcul",
  "tables in worksheet": "tableaux dans la feuille de calcul",
  "charts in worksheet": "graphiques dans la feuille de calcul",
  "all Planner plans associated with a group": "tous les plans du planificateur associés à un groupe",
  "all Planner tasks for a plan": "toutes les tâches de planificateur d’un plan",
  "my organization's default SharePoint site": "site SharePoint par défaut de mon organisation",
  "a SharePoint site by URL": "site SharePoint par URL",
  "subsites in a SharePoint site": "sous-sites dans un site SharePoint",
  "list in a SharePoint site ": "liste dans un site SharePoint ",
  "my notebooks": "mes blocs-notes",
  "my sections": "mes sections",
  "my pages": "mes pages",
  "my inbox rules": "mes règles de boîte de réception",
  "my outlook categories": "mes catégories Outlook",
  "get email headers": "obtenir des en-têtes d’e-mail",
  "list conference rooms": "répertorier les salles de conférence",
  "create notebook": "créer un bloc-notes",
  "create section": "créer une section",
  "create page": "créer une page",
  "Users": "Utilisateurs",
  "Users (beta)": "Utilisateurs (version bêta)",
  "Groups": "Groupes",
  "Groups (beta)": "Groupes (version bêta)",
  "Outlook Mail": "Messagerie Outlook",
  "Outlook Mail (beta)": "Messagerie Outlook (version bêta)",
  "Outlook Calendar": "Calendrier Outlook",
  "Outlook Calendar (beta)": "Calendrier Outlook (version bêta)",
  "Personal Contacts": "Contacts personnels",
  "OneDrive": "OneDrive",
  "Excel": "Excel",
  "Planner (beta)": "Planificateur (bêta)",
  "SharePoint Sites (beta)": "Sites SharePoint (bêta)",
  "SharePoint Lists": "Listes SharePoint",
  "OneNote (beta)": "OneNote (bêta)",
  "SharePoint Lists (beta)": "Listes SharePoint (bêta)",
  "Insights": "Informations",
  "Insights (beta)": "Informations (version bêta)",
  "Preview": "Aperçu",
  "People": "Contacts",
  "Extensions (beta)": "Extensions (version bêta)",
  "Batching": "Traitement par lots",
  "Extensions": "Extensions",
  "OneNote": "OneNote",
  "Planner": "Planner",
  "SharePoint Sites": "Sites SharePoint",
  "Microsoft Teams (beta)": "Microsoft Teams (version bêta)",
  "all buckets in Planner plan": "tous les compartiments dans le plan de planificateur",
  "all Planner tasks for user": "toutes les tâches de planificateur d’un utilisateur",
  "calculate loan payment": "calculer le paiement d’un emprunt",
  "channel info": "informations de canal",
  "channels of a team which I am member of": "canaux d’une équipe dont je suis membre",
  "Combine a POST and a GET": "Combiner une opération POST et une opération GET",
  "create a bucket in Planner plan": "créer un compartiment dans un plan de planificateur",
  "create a group with extension data": "créer un groupe avec les données d’extension",
  "create a Planner task": "créer une tâche de planificateur",
  "create an open extension": "créer une extension ouverte",
  "create channel": "créer un canal",
  "create chat thread": "créer un thread de conversation",
  "create user": "créer un utilisateur",
  "details for Planner task": "détails de la tâche de planificateur",
  "Enumerate list columns": "Énumérer les colonnes de liste",
  "Enumerate list content types": "Énumérer les types de contenu de liste",
  "Enumerate list items with specific column values": "Énumérer les éléments de liste avec des valeurs de colonne spécifiques",
  "Enumerate site columns of the root site": "Énumérer les colonnes de site du site racine",
  "Enumerate site content types of the root site": "Énumérer les types de contenu du site racine",
  "Enumerate subsites of the root site": "Énumérer les sous-sites du site racine",
  "Enumerate the document libraries under the root site": "Énumérer les bibliothèques de documents sous le site racine",
  "Enumerate the lists in the root site": "Énumérer les listes du site racine",
  "Enumerate the list items in a list": "Énumérer les éléments de liste d’une liste",
  "filter groups by extension property value": "filtrer des groupes par valeur de propriété d’extension",
  "get an open extension": "obtenir une extension ouverte",
  "get available schema extensions": "obtenir des extensions de schéma disponibles",
  "items in a team drive": "éléments d’un lecteur d’équipe",
  "members of a team": "membres d’une équipe",
  "my joined teams": "Équipes que j’ai rejointes",
  "my mails from an address": "mon courrier à partir d’une adresse",
  "people I work with": "personnes avec lesquelles je travaille",
  "people relevant to a topic": "personnes concernées par un sujet",
  "people whose name starts with J": "personnes dont le nom commence par J",
  "Perform parallel GETs": "Effectuer des opérations GET parallèles",
  "Planner plan": "plan de planificateur",
  "Planner task by id": "tâche de planificateur par ID",
  "Search for a SharePoint site by keyword": "Rechercher un site SharePoint par mot clé",
  "SharePoint site based on relative path of the site": "Site SharePoint basé sur le chemin d’accès relatif du site",
  "update a bucket in Planner plan": "mettre à jour un compartiment dans un plan de planificateur",
  "update a group with extension data": "mettre à jour un groupe avec les données d’extension",
  "update a Planner plan": "mettre à jour un plan de planificateur",
  "update a Planner task": "mettre à jour une tâche de planificateur",
  "update an open extension": "mettre à jour une extension ouverte",
  "user by email": "utilisateur par e-mail",
  "explorer-error": "Nous avons rencontré un problème lors de l’envoi de cette demande à l’API Graph.  Pour obtenir de l’aide, rejoignez-nous sur StackOverflow avec la balise [microsoftgraph].",
  "search my OneDrive": "rechercher mon espace OneDrive",
  "User Activities": "Activités utilisateur",
  "get recent user activities": "rechercher les activités utilisateur récentes",
  "create a user activity and history item": "créer un élément d’historique et une activité utilisateur"
}

loc_strings['ru-RU'] = {
  "Security (beta)": "Безопасность (бета-версия)",
  "alerts": "Оповещения",
  "alerts with 'High' severity": "Оповещения с высоким уровнем серьезности",
  "alerts related to 'ransomware' category": "Оповещения, связанные с категорией \"Программа-шантажист\"",
  "alerts from 'Azure Security Center'": "Оповещения из центра безопасности Azure",
  "alerts select by 'Title'": "Выбор оповещений по названию",
  "To try the explorer, please ": "Чтобы попробовать обозреватель, ",
  "sign in": "войдите",
  " with your work or school account from Microsoft.": " с помощью рабочей или учебной учетной записи от корпорации Майкрософт.",
  "Submit": "Отправить",
  "Using demo tenant": "Вы используете тестовую учетную запись.",
  "To access your own data:": "Для доступа к собственным данным:",
  "sign out": "выйти",
  "History": "Журнал",
  "Method": "Метод",
  "Query": "Запрос",
  "Status Code": "Код состояния",
  "Duration": "Срок действия",
  "Go": "Переход",
  "milliseconds": "мс",
  "YES": "ДА",
  "Show More": "Показать еще",
  "Graph Explorer": "Песочница Graph",
  "Failure": "Ошибка",
  "Success": "Успешно",
  "Authentication": "Проверка подлинности",
  "NO": "НЕТ",
  "request header": "Заголовки запроса",
  "Request body editor": "Редактор текста запроса",
  "Run Query": "Запуск запроса",
  "request body": "Текст запроса",
  "Close": "Закрыть",
  "Getting Started": "Начало работы",
  "Response": "Отклик",
  "login to send requests": "Войдите, чтобы изменить тип запроса",
  "HTTP verb selector": "Средство выбора HTTP-команд",
  "Share Query": "Поделиться запросом",
  "Share this link to let people try your current query in the Graph Explorer.": "Поделитесь этой ссылкой, чтобы другие пользователи могли попробовать ваш текущий запрос в песочнице Graph.",
  "Date": "Дата",
  "my profile": "мой профиль",
  "my files": "мои файлы",
  "my photo": "мои фото",
  "my mail": "моя почта",
  "my manager": "мой руководитель",
  "User photo": "фотография вошедшего пользователя",
  "Response Headers": "Заголовки откликов",
  "Response headers viewer": "Заголовки откликов, возвращаемые Microsoft Graph",
  "Response body": "Тело отклика, возвращаемое Microsoft Graph",
  "Response Preview": "Просмотр отклика",
  "Sample Queries": "Примеры запросов",
  "show more samples": "Показать другие примеры",
  "Sample Categories": "Примеры категорий",
  "On": "Вкл.",
  "Off": "Выкл.",
  "Remove All": "Удалить все",
  "Enter new header": "Введите новый заголовок",
  "Key": "Ключ",
  "Value": "Значение",
  "Login to try this request": "Войдите, чтобы выполнить этот запрос",
  "modify permissions": "изменить разрешения",
  "Save changes": "Сохранить изменения",
  "To change permissions, you will need to log-in again.": "Чтобы изменить разрешения, необходимо войти еще раз.",
  "all the items in my drive": "все элементы на моем диске",
  "items trending around me": "элементы, популярные в вашей компании",
  "my direct reports": "мои подчиненные",
  "all users in the organization": "все пользователи в организации",
  "all users in the Finance department": "все пользователи в отделе финансов",
  "my skills": "мои навыки",
  "all my Planner tasks": "все мои задачи в Планировщике",
  "track user changes": "отслеживание изменений пользователей",
  "all groups in my organization": "все группы в моей организации",
  "all groups I belong to": "все группы, в которые я вхожу",
  "unified groups I belong to": "объединенные группы, в которые я вхожу",
  "group members": "участники группы",
  "group's conversations": "беседы группы",
  "group's events": "события группы",
  "add favorite group": "добавить любимую группу",
  "items in a group drive": "элементы на диске группы",
  "track group changes": "отслеживание изменений в группах",
  "my high important mail": "моя почта высокой важности",
  "my mail that has 'Hello World'": "моя почта с фразой \"Hello World\"",
  "send an email": "отправить сообщение",
  "forward mail": "переслать сообщение",
  "track email changes": "отслеживание изменений в электронной почте",
  "email I'm @ mentioned": "сообщения, в которых меня упомянули @",
  "my events for the next week": "мои события на следующей неделе",
  "all events in my calendar": "все события в моем календаре",
  "all my calendars": "все мои календари",
  "all my event reminders for next week": "все напоминания о моих событиях на следующей неделе",
  "find meeting time": "найти время для собрания",
  "schedule a meeting": "запланировать собрание",
  "track changes on my events for the next week": "отслеживание изменений в моих событиях на следующей неделе",
  "my contacts": "мои контакты",
  "add contact": "добавить контакт",
  "my recent files": "мои последние файлы",
  "files shared with me": "файлы, к которым мне предоставлен доступ",
  "all of my excel files": "все мои файлы excel",
  "create a folder": "создать папку",
  "create session": "создать сеанс",
  "worksheets in a workbook": "листы в книге",
  "add a new worksheet": "добавить лист",
  "used range in worksheet": "используемый диапазон на листе",
  "tables in worksheet": "таблицы на листе",
  "charts in worksheet": "диаграммы на листе",
  "all Planner plans associated with a group": "все планы в Планировщике, связанные с группой",
  "all Planner tasks for a plan": "все задачи в Планировщик, связанные с планом",
  "my organization's default SharePoint site": "сайт SharePoint по умолчанию для моей организации",
  "a SharePoint site by URL": "сайт SharePoint по URL-адресу",
  "subsites in a SharePoint site": "дочерние сайты на сайте SharePoint",
  "list in a SharePoint site ": "список на сайте SharePoint ",
  "my notebooks": "мои записные книжки",
  "my sections": "мои разделы",
  "my pages": "Мои страницы",
  "my inbox rules": "Мои правила для папки \"Входящие\"",
  "my outlook categories": "Мои категории Outlook",
  "get email headers": "Получить заголовки для электронной почты",
  "list conference rooms": "Перечисление конференц-залов",
  "create notebook": "Создать записную книжку",
  "create section": "создать раздел",
  "create page": "создать страницу",
  "Users": "Пользователи",
  "Users (beta)": "Пользователи (бета-версия)",
  "Groups": "Группы",
  "Groups (beta)": "Группы (бета-версия)",
  "Outlook Mail": "Почта",
  "Outlook Mail (beta)": "Почта (бета-версия)",
  "Outlook Calendar": "Календарь Outlook",
  "Outlook Calendar (beta)": "Календарь Outlook (бета-версия)",
  "Personal Contacts": "Личные контакты",
  "OneDrive": "OneDrive",
  "Excel": "Excel",
  "Planner (beta)": "Планировщик (бета-версия)",
  "SharePoint Sites (beta)": "Сайты SharePoint (бета-версия)",
  "SharePoint Lists": "Списки SharePoint",
  "OneNote (beta)": "OneNote (бета-версия)",
  "SharePoint Lists (beta)": "Списки SharePoint (бета-версия)",
  "Insights": "Аналитика",
  "Insights (beta)": "Аналитика (бета-версия)",
  "Preview": "Предварительная версия",
  "People": "Люди",
  "Extensions (beta)": "Расширения (бета-версия)",
  "Batching": "Пакетная обработка",
  "Extensions": "Расширения",
  "OneNote": "OneNote",
  "Planner": "Планировщик",
  "SharePoint Sites": "Сайты SharePoint",
  "Microsoft Teams (beta)": "Microsoft Teams (бета-версия)",
  "all buckets in Planner plan": "Все сегменты в плане Планировщика",
  "all Planner tasks for user": "Все задачи в Планировщике для пользователя",
  "calculate loan payment": "Расчет выплаты ссуды",
  "channel info": "Сведения о канале",
  "channels of a team which I am member of": "Каналы группы, в которую я вхожу",
  "Combine a POST and a GET": "Объединение запросов POST и GET",
  "create a bucket in Planner plan": "Создание сегмента в плане Планировщика",
  "create a group with extension data": "Создание группы с данными расширения",
  "create a Planner task": "Создание задачи в Планировщике",
  "create an open extension": "Создание открытого расширения",
  "create channel": "Создание канала",
  "create chat thread": "Создание беседы в чате",
  "create user": "Создание пользователя",
  "details for Planner task": "Сведения о задаче в Планировщике",
  "Enumerate list columns": "Перечисление столбцов списка",
  "Enumerate list content types": "Перечисление типов контента списка",
  "Enumerate list items with specific column values": "Перечисление элементов списка с определенными значениями столбцов",
  "Enumerate site columns of the root site": "Перечисление столбцов корневого сайта",
  "Enumerate site content types of the root site": "Перечисление типов контента корневого сайта",
  "Enumerate subsites of the root site": "Перечисление дочерних сайтов корневого сайта",
  "Enumerate the document libraries under the root site": "Перечисление библиотек документов в корневом сайте",
  "Enumerate the lists in the root site": "Перечисление списков на корневом сайте",
  "Enumerate the list items in a list": "Перечисление элементов списка",
  "filter groups by extension property value": "Фильтрация групп по значению свойства расширения",
  "get an open extension": "Получение открытого расширения",
  "get available schema extensions": "Получение доступных расширений схемы",
  "items in a team drive": "Элементы объекта drive для рабочей группы",
  "members of a team": "Члены рабочей группы",
  "my joined teams": "Мои присоединенные рабочие группы",
  "my mails from an address": "Мои сообщения с адреса",
  "people I work with": "Люди, работающие со мной",
  "people relevant to a topic": "Люди, имеющие отношение к теме",
  "people whose name starts with J": "Люди, имя которых начинается с \"J\"",
  "Perform parallel GETs": "Параллельное выполнение запросов GET",
  "Planner plan": "План Планировщика",
  "Planner task by id": "Задачи в Планировщике по идентификатору",
  "Search for a SharePoint site by keyword": "Поиск сайта SharePoint по ключевому слову",
  "SharePoint site based on relative path of the site": "Сайт SharePoint на базе относительного пути сайта",
  "update a bucket in Planner plan": "Обновление сегмента в плане Планировщика",
  "update a group with extension data": "Обновление группы с данными расширения",
  "update a Planner plan": "Обновление плана Планировщика",
  "update a Planner task": "Обновление задачи в Планировщике",
  "update an open extension": "Обновление открытого расширения",
  "user by email": "Пользователи по электронной почте",
  "explorer-error": "Возникла проблема с отправкой этого запроса в API Graph.  Для получения помощи свяжитесь с нами через сайт StackOverflow, добавив к своему сообщению тег [microsoftgraph].",
  "search my OneDrive": "Поиск в OneDrive",
  "User Activities": "Действия пользователей",
  "get recent user activities": "Получение сведений о последних действиях пользователей",
  "create a user activity and history item": "Создание элемента журнала и действий пользователей"
}

loc_strings['en-US'] = {
  "Security (beta)": "Security (beta)",
  "alerts": "alerts",
  "alerts with 'High' severity": "alerts with 'High' severity",
  "alerts related to 'ransomware' category": "alerts related to 'ransomware' category",
  "alerts from 'Azure Security Center'": "alerts from 'Azure Security Center'",
  "alerts select by 'Title'": "alerts select by 'Title'",
  "To try the explorer, please ": "To try the explorer, please ",
  "sign in": "sign in",
  " with your work or school account from Microsoft.": " with your work or school account from Microsoft.",
  "Submit": "Submit",
  "Using demo tenant": "You are currently using a sample account.",
  "To access your own data:": "To access your own data:",
  "sign out": "sign out",
  "History": "History",
  "Method": "Method",
  "Query": "Query",
  "Status Code": "Status Code",
  "Duration": "Duration",
  "Go": "Go",
  "milliseconds": "ms",
  "YES": "YES",
  "Show More": "show more",
  "Graph Explorer": "Graph Explorer",
  "Failure": "Failure",
  "Success": "Success",
  "Authentication": "Authentication",
  "NO": "NO",
  "request header": "Request Headers",
  "Request body editor": "Request body editor",
  "Run Query": "Run Query",
  "request body": "Request Body",
  "Close": "Close",
  "Getting Started": "Getting Started",
  "Response": "Response",
  "login to send requests": "Login to change the request type",
  "HTTP verb selector": "HTTP verb selector",
  "Share Query": "Share Query",
  "Share this link to let people try your current query in the Graph Explorer.": "Share this link to let people try your current query in the Graph Explorer.",
  "Date": "Date",
  "my profile": "my profile",
  "my files": "my files",
  "my photo": "my photo",
  "my mail": "my mail",
  "my manager": "my manager",
  "User photo": "photo of the signed in user",
  "Response Headers": "Response Headers",
  "Response headers viewer": "The response headers returned by Microsoft Graph",
  "Response body": "The response body returned by Microsoft Graph",
  "Response Preview": "Response Preview",
  "Sample Queries": "Sample Queries",
  "show more samples": "show more samples",
  "Sample Categories": "Sample Categories",
  "On": "On",
  "Off": "Off",
  "Remove All": "Remove All",
  "Enter new header": "Enter new header",
  "Key": "Key",
  "Value": "Value",
  "Login to try this request": "Login to try this request",
  "modify permissions": "modify permissions",
  "Save changes": "Save changes",
  "To change permissions, you will need to log-in again.": "To change permissions, you will need to log-in again.",
  "all the items in my drive": "all the items in my drive",
  "items trending around me": "items trending around me",
  "my direct reports": "my direct reports",
  "all users in the organization": "all users in the organization",
  "all users in the Finance department": "all users in the Finance department",
  "my skills": "my skills",
  "all my Planner tasks": "all my Planner tasks",
  "track user changes": "track user changes",
  "all groups in my organization": "all groups in my organization",
  "all groups I belong to": "all groups I belong to",
  "unified groups I belong to": "unified groups I belong to",
  "group members": "group members",
  "group's conversations": "group's conversations",
  "group's events": "group's events",
  "add favorite group": "add favorite group",
  "items in a group drive": "items in a group drive",
  "track group changes": "track group changes",
  "my high important mail": "my high important mail",
  "my mail that has 'Hello World'": "my mail that has 'Hello World'",
  "send an email": "send an email",
  "forward mail": "forward mail",
  "track email changes": "track email changes",
  "email I'm @ mentioned": "email I'm @ mentioned",
  "my events for the next week": "my events for the next week",
  "all events in my calendar": "all events in my calendar",
  "all my calendars": "all my calendars",
  "all my event reminders for next week": "all my event reminders for next week",
  "find meeting time": "find meeting time",
  "schedule a meeting": "schedule a meeting",
  "track changes on my events for the next week": "track changes on my events for the next week",
  "my contacts": "my contacts",
  "add contact": "add contact",
  "my recent files": "my recent files",
  "files shared with me": "files shared with me",
  "all of my excel files": "all of my excel files",
  "create a folder": "create a folder",
  "create session": "create session",
  "worksheets in a workbook": "worksheets in a workbook",
  "add a new worksheet": "add a new worksheet",
  "used range in worksheet": "used range in worksheet",
  "tables in worksheet": "tables in worksheet",
  "charts in worksheet": "charts in worksheet",
  "all Planner plans associated with a group": "all Planner plans associated with a group",
  "all Planner tasks for a plan": "all Planner tasks for a plan",
  "my organization's default SharePoint site": "my organization's default SharePoint site",
  "a SharePoint site by URL": "a SharePoint site by URL",
  "subsites in a SharePoint site": "subsites in a SharePoint site",
  "list in a SharePoint site ": "list in a SharePoint site ",
  "my notebooks": "my notebooks",
  "my sections": "my sections",
  "my pages": "my pages",
  "my inbox rules": "my inbox rules",
  "my outlook categories": "my outlook categories",
  "get email headers": "get email headers",
  "list conference rooms": "list conference rooms",
  "create notebook": "create notebook",
  "create section": "create section",
  "create page": "create page",
  "Users": "Users",
  "Users (beta)": "Users (beta)",
  "Groups": "Groups",
  "Groups (beta)": "Groups (beta)",
  "Outlook Mail": "Outlook Mail",
  "Outlook Mail (beta)": "Outlook Mail (beta)",
  "Outlook Calendar": "Outlook Calendar",
  "Outlook Calendar (beta)": "Outlook Calendar (beta)",
  "Personal Contacts": "Personal Contacts",
  "OneDrive": "OneDrive",
  "Excel": "Excel",
  "Planner (beta)": "Planner (beta)",
  "SharePoint Sites (beta)": "SharePoint Sites (beta)",
  "SharePoint Lists": "SharePoint Lists",
  "OneNote (beta)": "OneNote (beta)",
  "SharePoint Lists (beta)": "SharePoint Lists (beta)",
  "Insights": "Insights",
  "Insights (beta)": "Insights (beta)",
  "Preview": "Preview",
  "People": "People",
  "Extensions (beta)": "Extensions (beta)",
  "Batching": "Batching",
  "Extensions": "Extensions",
  "OneNote": "OneNote",
  "Planner": "Planner",
  "SharePoint Sites": "SharePoint Sites",
  "Microsoft Teams (beta)": "Microsoft Teams (beta)",
  "all buckets in Planner plan": "all buckets in Planner plan",
  "all Planner tasks for user": "all Planner tasks for user",
  "calculate loan payment": "calculate loan payment",
  "channel info": "channel info",
  "channels of a team which I am member of": "channels of a team which I am member of",
  "Combine a POST and a GET": "Combine a POST and a GET",
  "create a bucket in Planner plan": "create a bucket in Planner plan",
  "create a group with extension data": "create a group with extension data",
  "create a Planner task": "create a Planner task",
  "create an open extension": "create an open extension",
  "create channel": "create channel",
  "create chat thread": "create chat thread",
  "create user": "create user",
  "details for Planner task": "details for Planner task",
  "Enumerate list columns": "Enumerate list columns",
  "Enumerate list content types": "Enumerate list content types",
  "Enumerate list items with specific column values": "Enumerate list items with specific column values",
  "Enumerate site columns of the root site": "Enumerate site columns of the root site",
  "Enumerate site content types of the root site": "Enumerate site content types of the root site",
  "Enumerate subsites of the root site": "Enumerate subsites of the root site",
  "Enumerate the document libraries under the root site": "Enumerate the document libraries under the root site",
  "Enumerate the lists in the root site": "Enumerate the lists in the root site",
  "Enumerate the list items in a list": "Enumerate the list items in a list",
  "filter groups by extension property value": "filter groups by extension property value",
  "get an open extension": "get an open extension",
  "get available schema extensions": "get available schema extensions",
  "items in a team drive": "items in a team drive",
  "members of a team": "members of a team",
  "my joined teams": "my joined teams",
  "my mails from an address": "my mails from an address",
  "people I work with": "people I work with",
  "people relevant to a topic": "people relevant to a topic",
  "people whose name starts with J": "people whose name starts with J",
  "Perform parallel GETs": "Perform parallel GETs",
  "Planner plan": "Planner plan",
  "Planner task by id": "Planner task by id",
  "Search for a SharePoint site by keyword": "Search for a SharePoint site by keyword",
  "SharePoint site based on relative path of the site": "SharePoint site based on relative path of the site",
  "update a bucket in Planner plan": "update a bucket in Planner plan",
  "update a group with extension data": "update a group with extension data",
  "update a Planner plan": "update a Planner plan",
  "update a Planner task": "update a Planner task",
  "update an open extension": "update an open extension",
  "user by email": "user by email",
  "explorer-error": "We had an issue sending this request to the Graph API.  For assistance, connect with us on StackOverflow with the tag [microsoftgraph].",
  "search my OneDrive": "search my OneDrive",
  "User Activities": "User Activities",
  "get recent user activities": "get recent user activities",
  "create a user activity and history item": "create a user activity and history item"
}

loc_strings['ja-JP'] = {
  "Security (beta)": "セキュリティ (ベータ版)",
  "alerts": "アラート",
  "alerts with 'High' severity": "重要度 - '高' のアラート",
  "alerts related to 'ransomware' category": "'ランサムウェア' カテゴリに関連するアラート",
  "alerts from 'Azure Security Center'": "'Azure Security Center' からのアラート",
  "alerts select by 'Title'": "'タイトル' で選択するアラート",
  "To try the explorer, please ": "エクスプローラーをお試しいただくには、Microsoft の職場または学校アカウントで ",
  "sign in": "サインイン",
  " with your work or school account from Microsoft.": " します。",
  "Submit": "送信",
  "Using demo tenant": "現在、サンプル アカウントを使用しています。",
  "To access your own data:": "自分のデータにアクセスするには:",
  "sign out": "サインアウト",
  "History": "履歴",
  "Method": "メソッド",
  "Query": "クエリ",
  "Status Code": "状態コード",
  "Duration": "期間",
  "Go": "実行",
  "milliseconds": "ミリ秒",
  "YES": "はい",
  "Show More": "さらに表示",
  "Graph Explorer": "Graph エクスプローラー",
  "Failure": "失敗",
  "Success": "成功",
  "Authentication": "認証",
  "NO": "いいえ",
  "request header": "要求ヘッダー",
  "Request body editor": "要求本文エディター",
  "Run Query": "クエリを実行",
  "request body": "要求本文",
  "Close": "閉じる",
  "Getting Started": "はじめに",
  "Response": "応答",
  "login to send requests": "要求の種類を変更するにはログインしてください",
  "HTTP verb selector": "HTTP 動詞セレクター",
  "Share Query": "クエリの共有",
  "Share this link to let people try your current query in the Graph Explorer.": "他のユーザーが Graph エクスプローラーで現在のクエリを試せるようにするには、このリンクを共有してください。",
  "Date": "日付",
  "my profile": "自分のプロファイル",
  "my files": "自分のファイル",
  "my photo": "自分の写真",
  "my mail": "自分のメール",
  "my manager": "自分の上司",
  "User photo": "サインインしているユーザーの写真",
  "Response Headers": "応答ヘッダー",
  "Response headers viewer": "Microsoft Graph で返される応答ヘッダー",
  "Response body": "Microsoft Graph で返される応答本文",
  "Response Preview": "応答のプレビュー",
  "Sample Queries": "サンプル クエリ",
  "show more samples": "サンプルをさらに表示",
  "Sample Categories": "サンプル カテゴリ",
  "On": "オン",
  "Off": "オフ",
  "Remove All": "すべて削除",
  "Enter new header": "新しいヘッダーを入力",
  "Key": "キー",
  "Value": "値",
  "Login to try this request": "ログインしてこの要求を試す",
  "modify permissions": "アクセス許可の修正",
  "Save changes": "変更の保存",
  "To change permissions, you will need to log-in again.": "アクセス許可を変更するには、もう一度ログインする必要があります。",
  "all the items in my drive": "自分のドライブ内のすべての項目",
  "items trending around me": "自分の周りで人気上昇中の項目",
  "my direct reports": "自分の直属の部下",
  "all users in the organization": "組織内のすべてのユーザー",
  "all users in the Finance department": "財務部門のすべてのユーザー",
  "my skills": "自分のスキル",
  "all my Planner tasks": "自分のすべてのプランナー タスク",
  "track user changes": "ユーザー変更の追跡",
  "all groups in my organization": "自分の組織内のすべてのグループ",
  "all groups I belong to": "自分の所属するすべてのグループ",
  "unified groups I belong to": "自分の所属する統合グループ",
  "group members": "グループ メンバー",
  "group's conversations": "グループの会話",
  "group's events": "グループのイベント",
  "add favorite group": "お気に入りのグループを追加する",
  "items in a group drive": "グループ ドライブ内の項目",
  "track group changes": "グループ変更の追跡",
  "my high important mail": "重要度の高い自分のメール",
  "my mail that has 'Hello World'": "'Hello World' を含む自分のメール",
  "send an email": "電子メールを送信する",
  "forward mail": "電子メールを転送する",
  "track email changes": "電子メール変更の追跡",
  "email I'm @ mentioned": "自分が @ メンションされている電子メール",
  "my events for the next week": "来週の自分の予定",
  "all events in my calendar": "自分の予定表のすべての予定",
  "all my calendars": "自分のすべての予定表",
  "all my event reminders for next week": "来週の自分のすべての予定のアラーム",
  "find meeting time": "会議の日時を検索する",
  "schedule a meeting": "会議の予約",
  "track changes on my events for the next week": "来週の自分の予定の変更の追跡",
  "my contacts": "連絡先",
  "add contact": "連絡先を追加する",
  "my recent files": "最近使ったファイル",
  "files shared with me": "自分と共有したファイル",
  "all of my excel files": "自分のすべての Excel ファイル",
  "create a folder": "フォルダーを作成する",
  "create session": "セッションを作成する",
  "worksheets in a workbook": "ブック内のワークシート",
  "add a new worksheet": "新しいワークシートを追加する",
  "used range in worksheet": "ワークシートの使用範囲",
  "tables in worksheet": "ワークシートのテーブル",
  "charts in worksheet": "ワークシートのグラフ",
  "all Planner plans associated with a group": "グループに関連付けられているすべてのプランナーの計画",
  "all Planner tasks for a plan": "計画のすべてのプランナー タスク",
  "my organization's default SharePoint site": "自分の組織の既定の SharePoint サイト",
  "a SharePoint site by URL": "URL ごとの SharePoint サイト",
  "subsites in a SharePoint site": "SharePoint サイト内のサブサイト",
  "list in a SharePoint site ": "SharePoint サイト内のリスト ",
  "my notebooks": "自分のノートブック",
  "my sections": "自分のセクション",
  "my pages": "自分のページ",
  "my inbox rules": "自分の受信トレイのルール",
  "my outlook categories": "自分の Outlook カテゴリ",
  "get email headers": "電子メール ヘッダーを取得する",
  "list conference rooms": "会議室をリスト表示する",
  "create notebook": "ノートブックを作成する",
  "create section": "セクションを作成する",
  "create page": "ページを作成する",
  "Users": "ユーザー",
  "Users (beta)": "ユーザー (ベータ版)",
  "Groups": "グループ",
  "Groups (beta)": "グループ (ベータ版)",
  "Outlook Mail": "Outlook メール",
  "Outlook Mail (beta)": "Outlook メール (ベータ版)",
  "Outlook Calendar": "Outlook カレンダー",
  "Outlook Calendar (beta)": "Outlook カレンダー (ベータ版)",
  "Personal Contacts": "個人用連絡先",
  "OneDrive": "OneDrive",
  "Excel": "Excel",
  "Planner (beta)": "Planner (ベータ版)",
  "SharePoint Sites (beta)": "SharePoint サイト (ベータ版)",
  "SharePoint Lists": "SharePoint リスト",
  "OneNote (beta)": "OneNote (ベータ版)",
  "SharePoint Lists (beta)": "SharePoint リスト (ベータ版)",
  "Insights": "Insights",
  "Insights (beta)": "Insights (ベータ版)",
  "Preview": "プレビュー",
  "People": "連絡先",
  "Extensions (beta)": "拡張機能 (ベータ版)",
  "Batching": "バッチ処理",
  "Extensions": "拡張機能",
  "OneNote": "OneNote",
  "Planner": "Planner",
  "SharePoint Sites": "SharePoint サイト",
  "Microsoft Teams (beta)": "Microsoft Teams (ベータ版)",
  "all buckets in Planner plan": "プランナーの計画内のすべてのバケット",
  "all Planner tasks for user": "ユーザーのすべての Planner タスク",
  "calculate loan payment": "ローンの支払を計算する",
  "channel info": "チャネル情報",
  "channels of a team which I am member of": "自分がメンバーであるチームのチャネル",
  "Combine a POST and a GET": "POST と GET を組み合わせる",
  "create a bucket in Planner plan": "プランナーの計画内にバケットを作成する",
  "create a group with extension data": "拡張データを含むグループを作成する",
  "create a Planner task": "プランナー タスクを作成する",
  "create an open extension": "オープン拡張機能を作成する",
  "create channel": "チャネルを作成する",
  "create chat thread": "チャット スレッドを作成する",
  "create user": "ユーザーを作成する",
  "details for Planner task": "Planner タスクの詳細",
  "Enumerate list columns": "リスト列を列挙する",
  "Enumerate list content types": "リスト コンテンツ タイプを列挙する",
  "Enumerate list items with specific column values": "特定の列の値を持つリスト項目を列挙する",
  "Enumerate site columns of the root site": "ルート サイトのサイト列を列挙する",
  "Enumerate site content types of the root site": "ルート サイトのサイト コンテンツ タイプを列挙する",
  "Enumerate subsites of the root site": "ルート サイトのサブサイトを列挙する",
  "Enumerate the document libraries under the root site": "ルート サイトのドキュメント ライブラリを列挙する",
  "Enumerate the lists in the root site": "ルート サイト内のリストを列挙する",
  "Enumerate the list items in a list": "リスト内のリスト項目を列挙する",
  "filter groups by extension property value": "拡張プロパティの値によってグループをフィルターする",
  "get an open extension": "オープン拡張機能を取得する",
  "get available schema extensions": "利用可能なスキーマ拡張を取得する",
  "items in a team drive": "チーム ドライブ内のアイテム",
  "members of a team": "チームのメンバー",
  "my joined teams": "結合された自分のチーム",
  "my mails from an address": "特定のアドレスからの自分のメール",
  "people I work with": "共に作業する人",
  "people relevant to a topic": "トピックに関連する人",
  "people whose name starts with J": "J で始まる名前を持つ人",
  "Perform parallel GETs": "GET を並列で実行する",
  "Planner plan": "Planner の計画",
  "Planner task by id": "ID ごとのプランナー タスク",
  "Search for a SharePoint site by keyword": "キーワードで SharePoint サイトを検索する",
  "SharePoint site based on relative path of the site": "サイトの相対パスに基づく SharePoint サイト",
  "update a bucket in Planner plan": "プランナーの計画内のバケットを更新する",
  "update a group with extension data": "拡張データを含むグループを更新する",
  "update a Planner plan": "プランナーの計画を更新する",
  "update a Planner task": "プランナー タスクを更新する",
  "update an open extension": "オープン拡張機能を更新する",
  "user by email": "メールごとのユーザー",
  "explorer-error": "この要求の Graph API への送信で問題が発生しました。 サポートが必要な場合は、StackOverflow で [microsoftgraph] タグを付けて質問を投稿してください。",
  "search my OneDrive": "自分の OneDrive を検索",
  "User Activities": "ユーザー アクティビティ",
  "get recent user activities": "最近のユーザー アクティビティを取得する",
  "create a user activity and history item": "ユーザー アクティビティと履歴項目を作成する"
}

loc_strings['zh-CN'] = {
  "Security (beta)": "安全 (beta)",
  "alerts": "警报",
  "alerts with 'High' severity": "严重性评为“高”的警报",
  "alerts related to 'ransomware' category": "与“勒索软件”类别相关的警报",
  "alerts from 'Azure Security Center'": "来自“Azure 安全中心”的警报",
  "alerts select by 'Title'": "按“标题”选择的警报",
  "To try the explorer, please ": "若要试用资源管理器，请执行以下操作 ",
  "sign in": "登录",
  " with your work or school account from Microsoft.": " 使用 Microsoft 提供的工作或学校帐户。",
  "Submit": "提交",
  "Using demo tenant": "当前使用的是示例帐户。",
  "To access your own data:": "若要访问你自己的数据:",
  "sign out": "注销",
  "History": "历史记录",
  "Method": "方法",
  "Query": "查询",
  "Status Code": "状态代码",
  "Duration": "持续时间",
  "Go": "调用",
  "milliseconds": "毫秒",
  "YES": "是",
  "Show More": "显示更多",
  "Graph Explorer": "Graph 浏览器",
  "Failure": "失败",
  "Success": "成功",
  "Authentication": "身份验证",
  "NO": "否",
  "request header": "请求头",
  "Request body editor": "请求正文编辑器",
  "Run Query": "运行查询",
  "request body": "请求正文",
  "Close": "关闭",
  "Getting Started": "开始使用",
  "Response": "响应",
  "login to send requests": "登录以更改请求类型",
  "HTTP verb selector": "HTTP 谓词选择器",
  "Share Query": "共享查询",
  "Share this link to let people try your current query in the Graph Explorer.": "共享此链接可让其他人在 Graph 浏览器中尝试执行当前查询。",
  "Date": "日期",
  "my profile": "我的个人资料",
  "my files": "我的文件",
  "my photo": "我的照片",
  "my mail": "我的邮件",
  "my manager": "我的管理器",
  "User photo": "已登录用户的照片",
  "Response Headers": "响应标头",
  "Response headers viewer": "由 Microsoft Graph 返回的响应标头",
  "Response body": "由 Microsoft Graph 返回的响应正文",
  "Response Preview": "响应预览",
  "Sample Queries": "示例查询",
  "show more samples": "显示更多示例",
  "Sample Categories": "示例类别",
  "On": "打开",
  "Off": "关闭",
  "Remove All": "全部删除",
  "Enter new header": "输入新标头",
  "Key": "键",
  "Value": "值",
  "Login to try this request": "登录以尝试此请求",
  "modify permissions": "修改权限",
  "Save changes": "保存更改",
  "To change permissions, you will need to log-in again.": "若要更改权限，必须重新登录。",
  "all the items in my drive": "我的驱动器中的所有项",
  "items trending around me": "我常用的项目",
  "my direct reports": "我的直接下属",
  "all users in the organization": "组织中的所有用户",
  "all users in the Finance department": "财务部门中的所有用户",
  "my skills": "我的技能",
  "all my Planner tasks": "我的所有规划器任务",
  "track user changes": "跟踪用户更改",
  "all groups in my organization": "我的组织中的所有组",
  "all groups I belong to": "我所属的全部组",
  "unified groups I belong to": "我所属的统一组",
  "group members": "组成员",
  "group's conversations": "组对话",
  "group's events": "组事件",
  "add favorite group": "添加收藏夹组",
  "items in a group drive": "组驱动器中的项",
  "track group changes": "跟踪组更改",
  "my high important mail": "我的高重要性邮件",
  "my mail that has 'Hello World'": "我的包含“Hello World”的邮件",
  "send an email": "发送电子邮件",
  "forward mail": "转发邮件",
  "track email changes": "跟踪电子邮件更改",
  "email I'm @ mentioned": "提及的我 @ 的电子邮件",
  "my events for the next week": "我的下周事件",
  "all events in my calendar": "我的日历中的所有事件",
  "all my calendars": "我的所有日历",
  "all my event reminders for next week": "我下周的所有事件提醒",
  "find meeting time": "查找会议时间",
  "schedule a meeting": "安排会议",
  "track changes on my events for the next week": "跟踪我的下周事件更改",
  "my contacts": "我的联系人",
  "add contact": "添加联系人",
  "my recent files": "我最近使用的文件",
  "files shared with me": "与我共享的文件",
  "all of my excel files": "我的所有 excel 文件",
  "create a folder": "创建文件夹",
  "create session": "创建会话",
  "worksheets in a workbook": "工作簿中的工作表",
  "add a new worksheet": "添加新的工作表",
  "used range in worksheet": "工作表中的使用区域",
  "tables in worksheet": "工作表中的表",
  "charts in worksheet": "工作表中的图表",
  "all Planner plans associated with a group": "与组关联的所有规划器计划",
  "all Planner tasks for a plan": "计划的所有规划器任务",
  "my organization's default SharePoint site": "我的组织的默认 SharePoint 网站",
  "a SharePoint site by URL": "SharePoint 网站(通过 URL)",
  "subsites in a SharePoint site": "SharePoint 网站中的子网站",
  "list in a SharePoint site ": "SharePoint 网站中的列表 ",
  "my notebooks": "我的笔记本",
  "my sections": "我的分区",
  "my pages": "我的页面",
  "my inbox rules": "我的收件箱规则",
  "my outlook categories": "我的 Outlook 类别",
  "get email headers": "获取电子邮件标头",
  "list conference rooms": "列出会议室",
  "create notebook": "创建笔记本",
  "create section": "创建分区",
  "create page": "创建页面",
  "Users": "用户",
  "Users (beta)": "用户 (beta)",
  "Groups": "组",
  "Groups (beta)": "组 (beta)",
  "Outlook Mail": "Outlook 邮件",
  "Outlook Mail (beta)": "Outlook 邮件 (beta)",
  "Outlook Calendar": "Outlook 日历",
  "Outlook Calendar (beta)": "Outlook 日历 (beta)",
  "Personal Contacts": "个人联系人",
  "OneDrive": "OneDrive",
  "Excel": "Excel",
  "Planner (beta)": "规划器 (beta)",
  "SharePoint Sites (beta)": "SharePoint 网站 (beta)",
  "SharePoint Lists": "SharePoint 列表",
  "OneNote (beta)": "OneNote (beta)",
  "SharePoint Lists (beta)": "SharePoint 列表 (beta)",
  "Insights": "见解",
  "Insights (beta)": "见解 (beta)",
  "Preview": "预览",
  "People": "人员",
  "Extensions (beta)": "扩展 (beta)",
  "Batching": "批处理",
  "Extensions": "扩展",
  "OneNote": "OneNote",
  "Planner": "Planner",
  "SharePoint Sites": "SharePoint 网站",
  "Microsoft Teams (beta)": "Microsoft Teams (beta)",
  "all buckets in Planner plan": "规划器计划中的所有存储桶",
  "all Planner tasks for user": "用户的所有规划器任务",
  "calculate loan payment": "计算贷款支付",
  "channel info": "频道信息",
  "channels of a team which I am member of": "我所属团队的频道",
  "Combine a POST and a GET": "结合 POST 和 GET",
  "create a bucket in Planner plan": "创建规划器计划中的存储桶",
  "create a group with extension data": "创建包含扩展数据的组",
  "create a Planner task": "创建规划器任务",
  "create an open extension": "创建开放扩展",
  "create channel": "创建频道",
  "create chat thread": "创建聊天会话",
  "create user": "创建用户",
  "details for Planner task": "规划器任务的详细信息",
  "Enumerate list columns": "枚举列表列",
  "Enumerate list content types": "枚举列表内容类型",
  "Enumerate list items with specific column values": "枚举具有特定的列值的列表项",
  "Enumerate site columns of the root site": "枚举根网站的网站栏",
  "Enumerate site content types of the root site": "枚举根网站的网站内容类型",
  "Enumerate subsites of the root site": "枚举根网站的子网站",
  "Enumerate the document libraries under the root site": "枚举根网站下的文档库",
  "Enumerate the lists in the root site": "枚举根网站中的列表",
  "Enumerate the list items in a list": "枚举列表中的列表项",
  "filter groups by extension property value": "按扩展属性值筛选组",
  "get an open extension": "获取开放扩展",
  "get available schema extensions": "获取可用的架构扩展",
  "items in a team drive": "团队驱动器中的项",
  "members of a team": "团队成员",
  "my joined teams": "我加入的团队",
  "my mails from an address": "我的邮件(来自地址)",
  "people I work with": "与我合作的人员",
  "people relevant to a topic": "与主题相关的人员",
  "people whose name starts with J": "姓名以 J 开头的人员",
  "Perform parallel GETs": "执行并行 GET",
  "Planner plan": "规划器计划",
  "Planner task by id": "按 ID 排序的规划器任务",
  "Search for a SharePoint site by keyword": "使用关键字搜索 SharePoint 网站",
  "SharePoint site based on relative path of the site": "基于网站相对路径的 SharePoint 网站",
  "update a bucket in Planner plan": "更新规划器计划中的存储桶",
  "update a group with extension data": "使用扩展数据更新组",
  "update a Planner plan": "更新规划器计划",
  "update a Planner task": "更新规划器任务",
  "update an open extension": "更新开放扩展",
  "user by email": "按电子邮件地址排序的用户",
  "explorer-error": "我们在向图形 API 发送此请求时遇到了问题。 若要获得帮助，请在 StackOverflow 上使用标签 [microsoftgraph] 与我们联系。",
  "search my OneDrive": "搜索我的 OneDrive",
  "User Activities": "用户活动",
  "get recent user activities": "获取最近用户活动",
  "create a user activity and history item": "创建用户活动和历史记录项"
}