// This is a generated file from bundleLocFiles.js 

export const loc_strings = {};

loc_strings['de-DE'] = {"To try the explorer, please ":"Um den Tester auszuprobieren, ","sign in":"Anmelden"," with your work or school account from Microsoft.":" mit Ihrem Geschäfts- oder Schulkonto von Microsoft an.","Submit":"Senden","Using demo tenant":"Verwenden des Demomandanten","sign out":"Abmelden","History":"Verlauf","Method":"Methode","Query":"Abfrage","Status Code":"Statuscode","Duration":"Dauer","Go":"OK","YES":"JA","NO":"NEIN","request header":"Anforderungsheader","request body":"Anforderungstextkörper","response":"Antwort","login to send requests":"Melden Sie an, um den Anforderungstyp zu ändern","Share Query":"Abfrage freigeben","Share this link to let people try your current query in the Graph Explorer.":"Teilen Sie diesen Link, damit Benutzer Ihre aktuelle Abfrage im Graph-Tester testen können."}

loc_strings['en-US'] = {"To try the explorer, please ":"To try the explorer, please ","sign in":"sign in"," with your work or school account from Microsoft.":" with your work or school account from Microsoft.","Submit":"Submit","Using demo tenant":"You are currently using a sample account.","To access your own data:":"To access your own data:","sign out":"Sign Out","History":"History","Method":"Method","Query":"Query","Status Code":"Status Code","Duration":"Duration","Go":"Go","YES":"YES","NO":"NO","request header":"request header","request body":"request body","response":"response","login to send requests":"Login to change the request type","Share Query":"Share Query","Share this link to let people try your current query in the Graph Explorer.":"Share this link to let people try your current query in the Graph Explorer."}

loc_strings['fr-FR'] = {"To try the explorer, please ":"Pour essayer l’afficheur, veuillez ","sign in":"se connecter"," with your work or school account from Microsoft.":" avec votre compte scolaire ou professionnel de Microsoft.","Submit":"Envoyer","Using demo tenant":"À l’aide du client de démonstration","sign out":"se déconnecter","History":"Historique","Method":"Méthode","Query":"Requête","Status Code":"Code d'état","Duration":"Durée","Go":"Rechercher","YES":"OUI","NO":"NON","request header":"en-tête de la demande","request body":"corps de la demande","response":"réponse"}

loc_strings['ru-RU'] = {"To try the explorer, please ":"Чтобы опробовать песочницу, ","sign in":"войти"," with your work or school account from Microsoft.":" с помощью рабочей или учебной учетной записи от корпорации Майкрософт.","Submit":"Отправить","Using demo tenant":"С помощью демонстрационного клиента","sign out":"выйти","History":"Журнал","Method":"Метод","Query":"Запрос","Status Code":"Код состояния","Duration":"Длительность","Go":"Перейти","YES":"ДА","NO":"НЕТ","request header":"заголовок запроса","request body":"текст запроса","response":"ответ"}

loc_strings['pt-BR'] = {"To try the explorer, please ":"Para experimentar o Explorador, ","sign in":"entrar"," with your work or school account from Microsoft.":" com a sua conta corporativa ou de estudante da Microsoft.","Submit":"Enviar","Using demo tenant":"Usando o Locatário de Demonstração","sign out":"sair","History":"Histórico","Method":"Método","Query":"Consulta","Status Code":"Código de Status","Duration":"Duração","Go":"Ir","YES":"SIM","NO":"NÃO","request header":"cabeçalho da solicitação","request body":"corpo da solicitação","response":"resposta"}

loc_strings['es-ES'] = {"To try the explorer, please ":"Para utilizar el probador, ","sign in":"iniciar sesión"," with your work or school account from Microsoft.":" con su cuenta profesional o educativa de Microsoft.","Submit":"Enviar","Using demo tenant":"Uso de inquilinos de demostración","sign out":"cerrar sesión","History":"Historial","Method":"Método","Query":"Consulta","Status Code":"Código de estado","Duration":"Duración","Go":"Ir","YES":"SÍ","NO":"NO","request header":"encabezado de solicitud","request body":"cuerpo de solicitud","response":"respuesta"}

loc_strings['ja-JP'] = {"To try the explorer, please ":"エクスプローラーをお試しいただくには、Microsoft の職場または学校アカウントで ","sign in":"サインイン"," with your work or school account from Microsoft.":" します。","Submit":"送信","Using demo tenant":"デモ テナントを使用しています","sign out":"サインアウト","History":"履歴","Method":"メソッド","Query":"クエリ","Status Code":"状態コード","Duration":"期間","Go":"検索","YES":"はい","NO":"いいえ","request header":"要求ヘッダー","request body":"要求本文","response":"応答","login to send requests":"要求の種類を変更するにはログインしてください","Share Query":"クエリの共有","Share this link to let people try your current query in the Graph Explorer.":"Graph エクスプローラーで現在のクエリを試せるようにするには、このリンクを共有してください。"}

loc_strings['zh-CN'] = {"To try the explorer, please ":"若要尝试浏览器，请 使用你的 Microsoft 工作或学校帐户","sign in":"登录"," with your work or school account from Microsoft.":"。","Submit":"提交","Using demo tenant":"使用演示租户","sign out":"注销","History":"历史记录","Method":"方法","Query":"查询","Status Code":"状态代码","Duration":"持续时间","Go":"转到","YES":"是","NO":"否","request header":"请求标题","request body":"请求正文","response":"响应","login to send requests":"登录以更改请求类型","Share Query":"共享查询","Share this link to let people try your current query in the Graph Explorer.":"共享此链接可让其他人在 Graph 浏览器中尝试执行当前查询。"}